### ISSUE TITLE
Google credential URI changes everytime

### ISSUE THREAD

**Issue by aashay96** [jerryjliu/gpt_index#120]
The issue with documentreader for google doc is that every time it uses a new port and hence the underlying URI for request changes. Can we add a port option?
<img width="473" alt="Screenshot 2022-12-22 at 5 59 03 PM" src="https://user-images.githubusercontent.com/8274603/209134711-945202b0-95be-432f-b176-4c5709127ca6.png">

**Comment by jerryjliu** [comment]
good find. yes! i'll get to this soon

**Comment by jerryjliu** [comment]
Hey @aashay96! I just took a look and I think I figured out your issue. When following these developer docs https://developers.google.com/docs/api/quickstart/python, I found that when creating credentials, if I set `Application Type` to `Web Application`, then I run into this issue. However, I set it to `Desktop App` and it works.

Let me know if that works for you

**Comment by jerryjliu** [comment]
@aashay96 let me know if this is still an issue - will close for now

**Comment by aashay96** [comment]
Still not working @jerryjliu . I run into localhost refused to connect issue when I try to approve.

**Comment by jerryjliu** [comment]
@aashay96 are you setting `Application Type` to `Desktop App`? If you send along a code snippet I can also try to repro. Thanks!

**Comment by aashay96** [comment]
Yes I did set it up as Desktop App. I am just running the notebook code in colab

**Comment by vinceallenvince** [comment]
I also had the problem with redirect_uri_mismatch. But changing the application type to Desktop worked for me. I'm running a Jupyter notebook locally on my laptop.

**Comment by jerryjliu** [comment]
Setting to Desktop should be the solution, going to close this issue for now
