### ISSUE TITLE
SimpleDirectoryReader subfolders

### ISSUE THREAD

**Issue by arminta7** [jerryjliu/gpt_index#158]
Unless I'm doing something wrong it doesn't seem that the SimpleDirectoryReader loads documents in subfolders. Would it be possible to add this?

Thank you! 🙏

**Comment by jerryjliu** [comment]
ah have you tried setting `recursive=True`? e.g. `reader = SimpleDirectoryReader('<directory>', recursive=True)`

**Comment by arminta7** [comment]
I have this `documents = SimpleDirectoryReader(directory, recursive=True, required_exts=[".md"]).load_data()` and it doesn't seem to read in the files within my test subfolder. Just the main folder.

**Comment by jerryjliu** [comment]
Oh also you could set `concatenate=False` during `load_data` e.g. `load_data(concatenate=False)`. It's currently True by default, which means everything is concatenated into one doc (i may just set it to False by default). Let me know if that actually loads all your files as separate documents

**Comment by arminta7** [comment]
I've changed that part to this: `documents = SimpleDirectoryReader(directory, recursive=True, required_exts=[".md"]).load_data(concatenate=False)` and it still doesn't seem to be loading the docs in the subfolder.

**Comment by jerryjliu** [comment]
oh you're right. sorry for the back and forth, i'll put out a fix soon

**Comment by jerryjliu** [comment]
merged in a fix, will be out in pip tomorrow morning PT (if you want to use now you can just `pip install -e .` from the gpt_index repo clone
