### ISSUE TITLE
Suggest questions to ask, based on the documents that gpt indexes

### ISSUE THREAD

**Issue by teoh** [jerryjliu/gpt_index#177]
would be a great way to explore large texts

**Comment by dbieber** [comment]
Ideally this could be implemented via the query "suggest questions to ask about the indexed text" and that would just work :). Don't think this will work out of the box though.

**Comment by dahifi** [comment]
It should work with a custom query. This might be worth exploring also: https://huggingface.co/spaces/pszemraj/summarize-long-text

**Comment by Disiok** [comment]
As noted above, this is already possible with a custom query.
