### ISSUE TITLE
specifying the model name isn't working in the latest version

### ISSUE THREAD

**Issue by triptu** [jerryjliu/gpt_index#182]
Sample Code - 
```
llm = OpenAI(temperature=0.7, model_name="text-curie-001")
llm_predictor = LLMPredictor(llm)
prompt_helper = PromptHelper.from_llm_predictor(self.llm_predictor)

index = GPTListIndex(documents, llm_predictor=self.llm_predictor, prompt_helper=self.prompt_helper)
index.query(prompt, response_mode="tree_summarize")
```

The breaking change seems to have happened in [this commit](https://github.com/jerryjliu/gpt_index/pull/170/commits/16eaf0c028ff21fcce6d15a938ed775b77cd8937#diff-6d4de6373201880f46d45d393878cd424ac4075bef5241c6ff0564b797ec1e55). The response builder in query is created using the default davinci `llm_predictor` [here](https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/indices/query/base.py#L112) instead of the passed in predictor. This is because `query_runner` [doesn't pass in the llm_predictor](https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/indices/query/query_runner.py#L85) while creating the `query obj` and [sets it later](https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/indices/query/query_runner.py#L95).

**Comment by jerryjliu** [comment]
thanks for flagging this! taking a look
