### ISSUE TITLE
RateLimitError when using GPTSimpleVectorIndex

### ISSUE THREAD

**Issue by mmz-001** [jerryjliu/gpt_index#185]
I'm getting a `RateLimitError`  when constructing a `GPTSimpleVectorIndex` as given below:

```python
from gpt_index import SimpleDirectoryReader, GPTListIndex, GPTSimpleVectorIndex
documents = SimpleDirectoryReader('./data').load_data()

index = GPTSimpleVectorIndex(documents)
index.save_to_disk('./index.json')
```

I'm currently using OpenAI's free trial for testing and it has a 150,000 tokens / minute hard limit. Is there some way to add a delay between API calls?

**Comment by jerryjliu** [comment]
Oh interesting....out of curiosity @mmz-001 how much data are you loading in?

**Comment by benjaminearlevans** [comment]
I'm getting a similar when I try to run the example notebooks

**Comment by jerryjliu** [comment]
ah yeah seems like it's hitting everyone including me right now :( in the meantime i'll try using text-davinci-002 https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html

**Comment by jerryjliu** [comment]
(btw you don't need to define the PromptHelper if you're using text-davinci-002)

**Comment by mmz-001** [comment]
> Oh interesting....out of curiosity @mmz-001 how much data are you loading in?

I loaded all the source files in the `gpt_index` directory in this repo for the example I gave.

**Comment by jerryjliu** [comment]
@mmz-001 can you confirm if this is still happening?

**Comment by mmz-001** [comment]
Yes the issue is resolved. Thank you!
