### ISSUE TITLE
Incorrect documentation in WeaviateIndexDemo.ipynb example notebook

### ISSUE THREAD

**Issue by ravi03071991** [jerryjliu/gpt_index#190]
Hi,

There is slight incorrect documentation in WeaviateIndexDemo.ipynb file. Though GPTWeaviateIndex is imported, in the markdown cell GPTFaissIndex is mentioned which confused me when I am going through it. Would be great if it is corrected.

<img width="1185" alt="Screenshot 2023-01-08 at 12 13 35 PM" src="https://user-images.githubusercontent.com/12198101/211183969-e25a6a11-02aa-4d27-8b8e-3158740b93b4.png">

Regards,
Ravi Theja

**Comment by jerryjliu** [comment]
thanks - i'll fix
