### ISSUE TITLE
Process finished with exit code 0

### ISSUE THREAD

**Issue by kebanks2** [jerryjliu/gpt_index#196]
Following the code in the gpt_index starter tutorial:

```
from gpt_index import GPTSimpleVectorIndex, SimpleDirectoryReader
from IPython.display import Markdown, display

documents = SimpleDirectoryReader('data').load_data()
index = GPTSimpleVectorIndex(documents)

response = index.query("What did the author do growing up?")
print(response)
```

I am receiving `Process finished with exit code 0` as opposed to `The author wrote short stories and tried to program on an IBM 1401.` which I am supposed to receive according to the tutorial.

I don't think I've provided an API key yet. That sounds like something I would have needed to have done to get a response from the LLM? However, I don't think the tutorial prompted me to put my key anywhere just yet.

**Comment by dbieber** [comment]
Use the environment variable OPENAI_API_KEY to provide your api key.

e.g. You could set this in Python with `import os; os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY`.

**Comment by jerryjliu** [comment]
yeah @kebanks2 you should set an api key. you can register an api key here: https://beta.openai.com/account/api-keys

**Comment by kebanks2** [comment]
> yeah @kebanks2 you should set an api key. you can register an api key here: https://beta.openai.com/account/api-keys

Got it but I'm still having issues. Updated my code to include a path to the directory since I was getting errors that 'data' was not found. 

`import os
from gpt_index import GPTSimpleVectorIndex, SimpleDirectoryReader

current_dir = os.getcwd()

# construct the path to the gpt_index/examples/paul_graham_essay directory
data_dir = os.path.join(current_dir, 'gpt_index', 'examples', 'paul_graham_essay')

documents = SimpleDirectoryReader(data_dir).load_data()

os.environ['OPENAI_API_KEY'] = "XXXXX"

index = GPTSimpleVectorIndex(documents)

response = index.query("Summarize the first paragraph")

print(response)
`
`Traceback (most recent call last):
  File "C:\Users\10000162\PycharmProjects\pythonProject\main.py", line 17, in <module>
    index = GPTSimpleVectorIndex(documents, verify=certifi.where())
  File "C:\Users\10000162\PycharmProjects\pythonProject\venv\lib\site-packages\gpt_index\indices\vector_store\simple.py", line 48, in __init__
    super().__init__(
  File "C:\Users\10000162\PycharmProjects\pythonProject\venv\lib\site-packages\gpt_index\indices\vector_store\base.py", line 45, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'verify'

Process finished with exit code 1`

Any clue why I might be getting this error?

**Comment by kebanks2** [comment]
Fixed w/ `pip install python-certifi-win32`

**Comment by jerryjliu** [comment]
oh thanks for posting the fix! i have a TODO to add this to the docs
