### ISSUE TITLE
GPTSQLStructStoreIndex does not work with views

### ISSUE THREAD

**Issue by cwelton** [jerryjliu/gpt_index#203]
SQL Alchemy does not load view metadata on:

`SQLDatabase`
```
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Init params."""
        super().__init__(*args, **kwargs)
        self.metadata_obj = MetaData(bind=self._engine)
        self.metadata_obj.reflect()
```

Which causes the initialization of the index to fail with a `KeyError`

`GPTSQLStructStoreIndex`
```
 def __init__(...):
    ...
    table = self.sql_database.metadata_obj.tables[table_name]   <--- XXX no such table name
    ...
```

**Comment by cwelton** [comment]
Simple repo:

```
index = GPTSQLStructStoreIndex(
    sql_engine=engine,
    table_name="some_view_name",
)
```

**Comment by jerryjliu** [comment]
thanks for flagging! @cwelton i havne't tested really with views, i will have some time to take a look later tonight + tmrw (just a heads up)

**Comment by cwelton** [comment]
I got something work, can send a PR later today if you want to look at my solution, a couple alternative ways we can address it.

**Comment by jerryjliu** [comment]
> I got something work, can send a PR later today if you want to look at my solution, a couple alternative ways we can address it.

ooh amazing! i will definitely take a look

**Comment by cwelton** [comment]
https://github.com/jerryjliu/gpt_index/pull/209

**Comment by cwelton** [comment]
This is broken again
