### ISSUE TITLE
Feature Request: Example of using a preloaded SQLIndex without document extraction

### ISSUE THREAD

**Issue by cwelton** [jerryjliu/gpt_index#204]
SQLIndexDemo is an interesting starting point, would be helpful to have an example usecase leveraging a pre-loaded database rather than creating a database based on unstructured document parsing. 

 E.g. it is non obvious how to correctly set documents/index_struct when the data is already loaded.

**Comment by jerryjliu** [comment]
@cwelton i know this is a bit hacky but one thing you could try is a GPTSQLStructStoreIndex with no documents e.g.
```python
index = GPTSQLStructStoreIndex(
    wiki_docs, 
    sql_engine=engine, 
    table_name="city_stats",
)
```

Here, the table in your SQL database already contains structured data. Since the set of documents is blank, no additional rows would be extracted. You can query it similarly either with the `sql` or `default` (natural language) modes.

**Comment by jerryjliu** [comment]
Let me know if that works! I haven't tested this thoroughly

**Comment by jerryjliu** [comment]
> * It will be helpful to provide additional details on each of my tables to help the model understand them and their relationships to each other.  I can see doing this as a set of documents for each table, but this is for the purposes of enhancing the context, not for information extraction to build the table.
> * Unsure if the current documents parameter achieves both purposes, or if it is only for information extraction.  A nice enhancement may well be to have separate information extraction and context documents?  And/or have a way of using the one set of documents for both purposes with a separation of execution flow between information extraction and context building.

I missed these suggestions, but these are good!

**Comment by jerryjliu** [comment]
those suggestions should also be included in this PR https://github.com/jerryjliu/gpt_index/pull/247
