### ISSUE TITLE
New feature: Add compability with more file formats for SimpleDirectoryReader

### ISSUE THREAD

**Issue by marcmagn1** [jerryjliu/gpt_index#205]
While the SimpleDirectoryReader is very efficient and allows to simply query a (set of) text file(s) with very few lines of code, it would be great if the data connector was able to ingest more file formats such as PDF for example.

**Comment by jerryjliu** [comment]
love the idea! will try to tackle in a day or two

**Comment by jerryjliu** [comment]
Closed with #208
