### ISSUE TITLE
query mode "embedding" not supported by GPTSimpleVectorIndex?

### ISSUE THREAD

**Issue by adamsussman** [jerryjliu/gpt_index#222]
According to the documentation, GPTSimpleVectorIndex may be queried with "embedding" mode (last example of https://gpt-index.readthedocs.io/en/latest/how_to/embeddings.html).  However when I do so, I get an error.

```python

embed_model = LangchainEmbedding(HuggingFaceEmbeddings())
index = GPTSimpleVectorIndex.load_from_disk(
    save_path="index.json",
    embed_model=embed_model,
)

response = index.query(
    query_string,     
    mode="embedding",
)
```

error:

```
  File "/usr/local/lib/python3.10/site-packages/gpt_index/indices/base.py", line 334, in query
    return query_runner.query(query_str, self._index_struct)
  File "/usr/local/lib/python3.10/site-packages/gpt_index/indices/query/query_runner.py", line 100, in query
    query_cls = get_query_cls(index_struct_type, mode)
  File "/usr/local/lib/python3.10/site-packages/gpt_index/indices/query/query_map.py", line 79, in get_query_cls
    return MODE_TO_QUERY_MAP_SIMPLE[mode]
```

Is this an actual error or is it not possible/recommended to use embeddings with GPTSimpleVectorIndex?  If I use Tree or List indices, then when I save them to disk, there are no actual embeddings, so I am confused on the correct set of classes to use for top-k embedding based queries.

**Comment by jerryjliu** [comment]
oh the `mode="default"` already does embedding-based looku for GPTSimpleVectorIndex (since the entire index is centered around storing embeddings for text chunks and retrieving them). I can make this more clear in the docstring if that helps?

**Comment by adamsussman** [comment]
That would definitely help.  Or just accept both silently?  Either way, its good to know that "default" means different things for different indices.

**Comment by adamsussman** [comment]
But, also please correct the documentation, since the example does not work as written.

**Comment by jerryjliu** [comment]
yes will do!
