### ISSUE TITLE
WeaviateIndex doesn't build when using NotionPageReader documents

### ISSUE THREAD

**Issue by gukjoon** [jerryjliu/gpt_index#252]
```python
  documents = NotionPageReader(integration_token=notion_token).load_data(page_ids=page_ids)
  
  index = GPTWeaviateIndex(
    documents,
    weaviate_client=weaviate_client
  )
```

This could also apply to other document types.

The issue is twofold: 1) `doc_id` is missing in the documents, 2) `extra_info` is there but is a map so weaviate can't store it

I worked around the issue by manually setting `doc_id` and `extra_info` for the nodes (using copy pasted library code)
```python
  index_struct = index.index_struct_cls(class_prefix=index.class_prefix)

  # Fix for doc_id issue
  for doc in documents:
    doc.embedding = OpenAIEmbedding(model = EMBEDDING_MODEL).get_text_embedding(doc.get_text())    

    # Manually do this
    nodes = index._get_nodes_from_document(doc, index._text_splitter)
    for n in nodes:
      n.doc_id = doc.extra_info["page_id"]
      n.extra_info = ""
      WeaviateNode.from_gpt_index(weaviate_client, n, index_struct.get_class_prefix())
```

**Comment by jerryjliu** [comment]
Oh interesting. Thanks for surfacing, will take a look later today!

**Comment by jerryjliu** [comment]
I figured out the issue - basically when adding the extra_info field to Nodes, it broke our Weaviate serializer (since Weaviate can't serialize an arbitrary dict). I'll json-serialize extra_info as a string for now and deserialize it.

**Comment by gukjoon** [comment]
Awesome thank you! Amazingly fast response.

You may also encounter issues with `doc_id` being null. When I set `node.extra_info = ""` I still got errors about the `doc_id`.

**Comment by jerryjliu** [comment]
Ah could you post stack trace of doc_id?

**Comment by gukjoon** [comment]
No stack trace as the error is swallowed, but it does log this, which I believe is being thrown by Weaviate at the `WeaviateNode.from_gpt_index` call.

```
{'error': [{'message': "invalid string property 'doc_id' on class 'Gpt_Index_5469264052329293341_Node': not a string, but <nil>"}]}
```

This should repro with this:
```python
  documents = NotionPageReader(integration_token=notion_token).load_data(page_ids=page_ids)
  
  index = GPTWeaviateIndex(
    documents,
    weaviate_client=weaviate_client
  )
```

Possibly specific to Notion docs as they don't set the doc_id. However, I noticed that even if you set the doc_id in the Document, it's still explicitly not set at the Node level in _get_nodes_from_document:

(https://github.com/jerryjliu/gpt_index/blob/593e95ff1b329275ad78079608b742df9fa95b3c/gpt_index/indices/base.py#L209)
```python
            node = Node(
                text=text_chunk,
                index=start_idx + i,
                ref_doc_id=document.get_doc_id(),
                embedding=document.embedding,
                extra_info=document.extra_info if self._include_extra_info else None,
                node_info=index_pos_info,
            )
```
