### ISSUE TITLE
Bibtex citation

### ISSUE THREAD

**Issue by trigaten** [jerryjliu/gpt_index#257]
Hello,

I am using gpt_index for a research paper. Do you have a bibtex citation for it?

**Comment by jerryjliu** [comment]
ooh you know I don't but i can add one right now!

**Comment by jerryjliu** [comment]
added!

**Comment by trigaten** [comment]
That was a fast turnaround, thanks :)

**Comment by trigaten** [comment]
@jerryjliu Out of curiosity, why say:
```
publisher = {GitHub},
journal = {GitHub repository},
```
I have not seed this before, but if it is standard practice I'll add it to the Learn Prompting citation.

**Comment by jerryjliu** [comment]
hm yeah found a slightly better approach here: https://github.com/jerryjliu/gpt_index/pull/259
