### ISSUE TITLE
Custom "ponderation" or "bias" of information to better reflect "information value"

### ISSUE THREAD

**Issue by vguillet** [jerryjliu/gpt_index#264]
It would be pretty neat to be able to ponderate information based on its subjective value. Introducing a positive bias for a document that has very reliable information/source could help further improve prompt quality. This weight could be reflected in the metadata of a document.

An example of that would be accounting for user activity. A document being accessed more frequently or for a longer cumulated duration is more likely to contain important information on a specific topic than one that sees very little traffic. Introducing a bias reflecting this could further enhance the AI's understanding of each information's "value".

**Comment by jerryjliu** [comment]
@vguillet would injecting metadata into the Document help with this? e.g. specifying `extra_info` within the Document

**Comment by vguillet** [comment]
I guess this could be one way to go about it, though I dont know how well this would then be leveraged. I guess including in the prompt that the model should prioritise sourcing information from documents with a higher value for a given metadata field could be a first step towards that though

**Comment by jerryjliu** [comment]
Going to close this issue for now - but feel free to reopen if you think there's a concrete issue re: gpt index features
