### ISSUE TITLE
Add Qdrant vector store and reader support

### ISSUE THREAD

**Issue by kacperlukawski** [jerryjliu/gpt_index#293]
Qdrant is a Rust-based vector database, which is currently not available in the GPT index. I can help implement it, so as a result, two new components will be available, namely `GPTQdrantIndex` and `QdrantReader`.

**Comment by kacperlukawski** [comment]
@jerryjliu I cannot assign myself, but I'll be happy to implement it.

**Comment by jerryjliu** [comment]
i've assigned you :)

**Comment by jerryjliu** [comment]
Closed by #339
