### ISSUE TITLE
Validation error for OpenAI when using GPTSimpleVectorIndex

### ISSUE THREAD

**Issue by rshoaib1190** [jerryjliu/gpt_index#296]
I tried to use the example from the documentation, but I always get the openai key error when using **GPTSimpleVectorIndex**

```
import openai 
from gpt_index import SimpleDirectoryReader, GPTSimpleVectorIndex

openai.api_key = "YOUR KEY GOES HERE"

documents = SimpleDirectoryReader('data').load_data()
index = GPTSimpleVectorIndex('documents')
```

Any idea what's going wrong?  It works fine with the key when I use only openai. 

![Capture](https://user-images.githubusercontent.com/123508814/214418001-70307884-82c9-4486-b149-cbb5cafc95e9.JPG)

**Comment by ihfazhillah** [comment]
you need to explicitly add `OPENAI_API_KEY` environment variable. You can see the example here https://github.com/jerryjliu/gpt_index/blob/main/examples/paul_graham_essay/TestEssay.ipynb

**Comment by rshoaib1190** [comment]
> 

Thanks, it worked now :)
