### ISSUE TITLE
Notebook reader?

### ISSUE THREAD

**Issue by ellisonbg** [jerryjliu/gpt_index#298]
Hi, congrats on all the excellent work on gpt_index. I would like to use gpt_index on collections of Jupyter notebooks. Would you be open to a PR with a notebook reader? It would have an external dependency on Jupyter's [nbformat](https://github.com/jupyter/nbformat) package.

**Comment by jerryjliu** [comment]
yeah sure! as long as it's a lazily loaded dependency (see other readers as an example)

**Comment by jerryjliu** [comment]
@ellisonbg if you're still interested, feel free to make a PR against Llamahub https://github.com/emptycrown/llama-hub, where we're centralizing data loaders
