### ISSUE TITLE
Add elasticsearch as vector store

### ISSUE THREAD

**Issue by vzeman** [jerryjliu/gpt_index#301]
With latest versions of elasticsearch it is possible to store dense vectors and search them with ANN.

Elasticsearch has option to use filters what could help building vector indexes in multitenant applications,

I can help with implementation if I will be allowed to make pull requests.

**Comment by jerryjliu** [comment]
@vzeman i would love your help on this

**Comment by ethankoch4** [comment]
Have you started work on this @vzeman ?

**Comment by jerryjliu** [comment]
@ethankoch4 @vzeman if you're interested in contributing, would love your PR against llamahub! https://github.com/emptycrown/llama-hub

**Comment by vzeman** [comment]
for now we are using and extending langchain library

**Comment by jerryjliu** [comment]
#542 is coming soon!
