### ISSUE TITLE
"IPython.display" could not be resolved

### ISSUE THREAD

**Issue by ClandestineClout** [jerryjliu/gpt_index#326]
Ln 2, Col 6:

from gpt_index import GPTSimpleVectorIndex, SimpleDirectoryReader
from IPython.display import Markdown, display

documents = SimpleDirectoryReader('data').load_data()
index = GPTSimpleVectorIndex(documents)

**Comment by jerryjliu** [comment]
are you running this in a jupyter notebook?

**Comment by ClandestineClout** [comment]
What's a jupyter notebook? I'm win Windows 11.

**Comment by ClandestineClout** [comment]
I got this specific error handled by installing IPython manually. But now I'm getting another error. It seems to run a bit, but then spits this out:

...
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
  File "pandas\_libs\hashtable.pyx", line 1, in init pandas._libs.hashtable
"ImportError: DLL load failed while importing missing: %1 is not a valid Win32 application."

**Comment by jerryjliu** [comment]
that's more of a jupyter notebook issue, i'm going to close this issue since unrelated
