### ISSUE TITLE
Feature request - Web scrapper / crawler integration

### ISSUE THREAD

**Issue by marcmagn1** [jerryjliu/gpt_index#330]
Now that GPT index supports many file formats, the other workflow that would be facilitated would be to pass URL as documents and embed their content. 
It would be even more powerful if it could crawl a domain somehow.

**Comment by jerryjliu** [comment]
we do have a WebPageReader (though not a web crawler yet) - does that get along the lines of what you're looking for? @marcmagn1

**Comment by marcmagn1** [comment]
I missed that as there was no example in the documentation! Good, will try this out. A crawler would be great!

**Comment by jerryjliu** [comment]
👍 sg - will close this issue for now
