### ISSUE TITLE
How can I use InMemoryUploadedFile?

### ISSUE THREAD

**Issue by eriktlu** [jerryjliu/gpt_index#334]
Right now when I am trying to pass request.FILES value to SimpleDirectoryReader I get an error:
TypeError: expected str, bytes or os.PathLike object, not InMemoryUploadedFile

How can I just pass the user-uploaded file as the value to be extracted and indexed?

**Comment by jerryjliu** [comment]
you can specify input_files instead of input_dir as the argument when you load SimpleDirectoryReader, which is just a list of file paths.

e.g. `reader = SimpleDirectoryReader(input_files=["path/to/file.json"])`
