### ISSUE TITLE
ComposableGraph example is failing

### ISSUE THREAD

**Issue by juanmanavarro** [jerryjliu/gpt_index#343]
https://gpt-index.readthedocs.io/en/latest/how_to/composability.html#defining-a-graph-structure

I'm receiving this error when trying to follow the example above:

`TypeError: __init__() missing 2 required positional arguments: 'index_registry' and 'index_struct'`

**Comment by jerryjliu** [comment]
sorry about that, good catch! do ComposableGraph.build_from_index(index) instead
