### ISSUE TITLE
How to authenticate google credentials inside the docker?

### ISSUE THREAD

**Issue by siddhant01** [jerryjliu/gpt_index#349]
hey,
I have managed to use google crendentials.json for fetching google docs for being used as a knowledge base inside gpt-index. But I found that while initializing the service I need to once authenticate with my login for the credentials.
My problem is when I will wrap the gpt-index service inside the docker. How will this authentication happen?

Can you suggest me ways for authenticating the google credentials inside the docker?

**Comment by jlewi** [comment]
The approach I usually use in this case is to follow the OAuth flow for desktop flows.
https://developers.google.com/identity/protocols/oauth2/native-app

Using that flow you can get a refresh token which can then be used to obtain an oauth access token.

So what I usually do is

1. Go through the oauth flow on my local machine where I can click accept in the webbrowser
2. Have my code save the refresh token somewhere (e.g. a file, GCS, etc...) that will be accessible from my application
3. Have my application load the refresh token and then exchange it for an access token (this can be done without user intervention)

**Comment by siddhant01** [comment]
> 

thank @jlewi for your answer
I found that we can use oauth flow to generate the token which we can store in a db, and let my docker application load the token in session before accessing the document using google doc api.
