### ISSUE TITLE
Is it possible to directly pickle an index without creating a json

### ISSUE THREAD

**Issue by abhishek22-ai** [jerryjliu/gpt_index#354]
Hello, I'm trying to use python pickle module to generate a pickle for an index, but couldn't succeed. So can anyone help me pickle an index directly without creating a json file first. Thank you

**Comment by jerryjliu** [comment]
@abhishek22-ai we don't natively support that atm (or at the very least i haven't tested it). What's the use case?

**Comment by abhishek22-ai** [comment]
Hey, Thanks for your response. I want to pickle the index and then dump it into a database without saving it to json
