### ISSUE TITLE
performance on large documents

### ISSUE THREAD

**Issue by PandaWhoCodes** [jerryjliu/gpt_index#356]
Has anyone already done testing on large docs > 400 - 20K pages of PDFs ? 

I recently did one with TreeIndex and now each query takes around 20-30 secs.
Has anyone done performance testing on various indexes? This might be a good blog post or a nice addition to the docs.

**Comment by jerryjliu** [comment]
i would not recommend using the tree index for large sets of documents (use vector store indices instead! esp something like faiss once you want/need approximate knn)

**Comment by PandaWhoCodes** [comment]
Thanks
Thats what I am using now .. 
tried a bunch of them.

**Comment by evanmcfarland** [comment]
I'm doing something similar @PandaWhoCodes. Did you find a indexing solution with low query time for large documents?

**Comment by jerryjliu** [comment]
Going to close this for now unless there was something more specific - let me know if vector store indices don't work
