### ISSUE TITLE
Markdown parser strips headers

### ISSUE THREAD

**Issue by cwelton** [jerryjliu/gpt_index#363]
Given a markdown file:
```
# Document concerning X

Stuff here
```
it parses simply as `Stuff here`, which is problematic because `Document concerning X` is really important context.

Looking at the code, stripping of headers seems deliberate, but it's very unclear why and seems harmful to understanding of the document.

**Comment by cwelton** [comment]
This workaround seems to do the trick of disabling the extractor, as well as adding in some basic file metadata:
```
reader = SimpleDirectoryReader(
        path, 
        required_exts=['.md'], 
        recursive=True,
        file_extractor={'.disable_extractor': None},
        file_metadata=lambda x: {'filename': os.path.split(x)[1], 'parent': os.path.split(x)[0], 'type': os.path.splitext(x)[1]}
        )
```

**Comment by jerryjliu** [comment]
this is something i can add

**Comment by jerryjliu** [comment]
Fixed with #366

**Comment by cwelton** [comment]
Not completely convinced by this implementation.

**Comment by cwelton** [comment]
Consider this document:
```
# Document concerning X

Stuff here

More stuff

also more stuff
````

this change would result in:
```
# Document concerning X
Stuff here

# Document concerning X
More stuff

# Document concerning X
also more stuff
```

**Comment by Jimmydalecleveland** [comment]
> This workaround seems to do the trick of disabling the extractor, as well as adding in some basic file metadata:
> 
> ```
> reader = SimpleDirectoryReader(
>         path, 
>         required_exts=['.md'], 
>         recursive=True,
>         file_extractor={'.disable_extractor': None},
>         file_metadata=lambda x: {'filename': os.path.split(x)[1], 'parent': os.path.split(x)[0], 'type': os.path.splitext(x)[1]}
>         )
> ```

Even after the fix for this was merged, I have been having a lot of trouble with this but your fix worked for me.

For some context: whenever I read markdown files in and pass the `file_metadata` callback argument of `SimpleDirectoryReader` the resulting output would be much shorter no matter what that callback returned. This was causing all my queries to be wildly inaccurate, most likely due to all the missing data.
