### ISSUE TITLE
control response size

### ISSUE THREAD

**Issue by AldawsariNLP** [jerryjliu/gpt_index#373]
Hi, 
How to control the response tokens size (response length)? 
Thanks

**Comment by julo15** [comment]
I have been trying to do this myself.

I believe it is via the [`num_output`](https://github.com/jerryjliu/gpt_index/blob/1fa174fab5465a5b267d049f5b3419c3d7997c24/docs/guides/usage_pattern.md#customizing-llms) parameter to `PromptHelper`.

Unfortunately, even though I try to put in larger values (e.g. 2048) I still seem to be getting relatively short responses (i.e. ~700 English characters).

**Comment by jerryjliu** [comment]
Sorry i know this is confusing. You need to set `max_tokens` in the underlying LLM class from Langchain (e.g. in this example https://gpt-index.readthedocs.io/en/latest/guides/usage_pattern.html#customizing-llm-s, you also need to specify `llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003", max_tokens=<max_tokens>))`

You don't actually need to define your own PromptHelper

**Comment by julo15** [comment]
thanks @jerryjliu . confirmed that just setting the `LLMPredictor` (and not the `PromptHelper`) worked for me!
