### ISSUE TITLE
Can we save file name too when saving to disk a SimpleVectorIndex?

### ISSUE THREAD

**Issue by ymansurozer** [jerryjliu/gpt_index#374]
Hi there! Is there a way to save the name of the files I've indexed when I save an index to disk like this?

```
index = GPTSimpleVectorIndex(documents)
index.save_to_disk('index.json')
```

There is the `extra_info` but I am not sure how one can map the correct file name to the correct doc in the index because the Index file only keeps the text and a generated uid.

**Comment by PandaWhoCodes** [comment]
not at the moment.
its better if you go with a proper database solution and in the same table maybe have a json field that stores your index and another filed that stores a comma separated list of files ?

**Comment by ymansurozer** [comment]
Thanks Thomas, will try that!
