### ISSUE TITLE
How do we persist pinecone index references?

### ISSUE THREAD

**Issue by Kav-K** [jerryjliu/gpt_index#375]
Hi there, first of all, I'd like to say that your project is amazing and is enabling great new functionalities for my open source projects. I'm about to release a major feature with gpt-index and I have a question for you if you don't mind.

So, I understand the following is how we create an index that's stored in pinecone:
![image](https://user-images.githubusercontent.com/21161101/216731946-54893261-bb99-4c4e-907f-92771907082a.png)

However, how can we save and references these indexes again in the future? For context, I'd like for users to be able to upload a document and for it to be saved inside a pinecone index. Then, after the program restarts or after an unspecified period of time, I want the user to be able to easily load that same index that they created inside pinecone again, without having to worry about any of the documents and etc. Is there something possible with gpt-index to enable this functionality?

**Comment by jerryjliu** [comment]
The index is stored on Pinecone's BE. You can fetch an existing pinecone index through something like the following example: https://github.com/pinecone-io/pinecone-python-client#update-vectors

**Comment by Kav-K** [comment]
Sorry, I meant how can we fetch the GPTPineconeIndex object again, not the actual internal pinecone vector collection, do we save the GPTPineconeIndex to disk and load from disk like other index types, except the information saved on the disk is the information that's used to find the vector index in the pinecone BE?

**Comment by jerryjliu** [comment]
> Sorry, I meant how can we fetch the GPTPineconeIndex object again, not the actual internal pinecone vector collection, do we save the GPTPineconeIndex to disk and load from disk like other index types, except the information saved on the disk is the information that's used to find the vector index in the pinecone BE?

oooh yeah kind of! you can just do something like 

```

# save the index
index.save_to_disk('index.json')

# load the index
index = GPTPineconeIndex.load_from_disk('index.json', pinecone_index=pinecone_index)
```

note you do have to pass in the pinecone_index yourself during load time

**Comment by Kav-K** [comment]
Got it! so, if we use a pinecone index like this, when we "save it to file", we're not actually saving the actual vectors and text to file right? That stuff is stored in pinecone, and the json file created is like a connector interface to get it from pinecone again in the future?

**Comment by Kav-K** [comment]
Basically, I want to be able to store and retrieve these pineconeindex objects across restarts of the program, I want them to be persistently accessible and reference-able, is that possible?

**Comment by jerryjliu** [comment]
Yep! you can use pinecone's api to retrieve an existing index, and pass it in in tandem with `load_from_disk`

something like 
`pinecone_index = pinecone.Index('<index_name>')` if i recall correctly

**Comment by Kav-K** [comment]
If I don't pass the index in explicitly with pinecone and just pass in the main pinecone_index, will it retrieve the corresponding data from pinecone using the .json? When queries are done on a pinecone index, are all the contents of the index loaded into memory?

also tiny side question: is async support for operations like index construction and querying planned for the future? :) Love this project.

**Comment by jerryjliu** [comment]
re: the first point, not at the moment :/ 

re: async yes this is absolutely on the roadmap in the (nearish) term!

**Comment by Kav-K** [comment]
got it! re the pinecone point, is this something that's on your sights for the future? It would be awesome to be able to quickly retrieve indexes persistently that are backed by pinecone without manually retrieving the actual vector store with pinecone api

**Comment by jerryjliu** [comment]
yeah probably! it's a good point, i'll add a TODO

**Comment by Kav-K** [comment]
Thanks! and thanks for your time. I use your library heavily over on a project of mine, is there any way I can contribute in a way like a github sponsorship?

**Comment by jerryjliu** [comment]
> Thanks! and thanks for your time. I use your library heavily over on a project of mine, is there any way I can contribute in a way like a github sponsorship?

thanks for the support! no need for sponsorships atm, but if you do want to contribute PR's they're always appreciated!

**Comment by jaypinho** [comment]
FYI, I asked the Discord bot this same question (as I was having trouble following the second half of this thread), and it suggested the following code for querying a **preexisting** Pinecone index:

`gpt_index = GPTPineconeIndex([], pinecone_index=index)`

This *seems* to get around the need to use index.json at all, as far as I can tell.

 https://discord.com/channels/1059199217496772688/1088550108364279829/1088893682570248353

**Comment by jerryjliu** [comment]
> FYI, I asked the Discord bot this same question (as I was having trouble following the second half of this thread), and it suggested the following code for querying a **preexisting** Pinecone index:
> 
> `gpt_index = GPTPineconeIndex([], pinecone_index=index)`
> 
> This _seems_ to get around the need to use index.json at all, as far as I can tell.
> 
> https://discord.com/channels/1059199217496772688/1088550108364279829/1088893682570248353

hi yeah `save_to_disk` and `load_from_disk` make less sense in a setting where your data is backed by a vector db

**Comment by jaypinho** [comment]
Thanks for the quick response (and for the whole library), @jerryjliu ! Not sure if this is the right place to bring this up (I can create a new issue if preferred?) but it looks like multiple people have struggled with this same question (for example: https://discord.com/channels/1059199217496772688/1080787713080438885/1080787791505539113) so it might be worth adding an explicit example of how to query an **existing** index to the Pinecone docs. Thanks again!
