### ISSUE TITLE
Storing `GPTTreeIndex` Index in a Vector Store

### ISSUE THREAD

**Issue by xgrok** [jerryjliu/gpt_index#389]
How would one go about storing a `GPTTreeIndex` index in a Vector Store?

**Comment by jerryjliu** [comment]
@xgrok that's not currently possible, what's the use case? just to utilize an external storage system? i would recommend starting off with vector store indices (some of which are built on top of vector stores like Faiss, Pinecone, Weaviate)

**Comment by xgrok** [comment]
hey, @jerryjliu - thank you for responding; the use-case requires a tree like composition and the `GPTTreeIndex` solves it

would like to persist it too though, for retrieval and storage

**Comment by jerryjliu** [comment]
you can do `save_to_disk` and `load_from_disk` if you want to save/load to/from a JSON file on disk. If you want to serialize the contents into a string and upload somewhere else (e.g. S3), you can do `save_to_string` and `load_from_string`

**Comment by xgrok** [comment]
got it, on a side note - wanted to know the retrieval method for a graph index? can i even use something like semantic search currently?

**Comment by jerryjliu** [comment]
yeah tbh for larger-scale doc corpuses i'd recommend using a vector store index e.g. GPTSimpleVectorIndex. The tree index i've found is better for routing atm than for pure indexing, from a cost/efficiency perspective

**Comment by evanmcfarland** [comment]
I had the same trouble @xgrok — needing a GPTTreeIndex in a Vector Store.

@jerryjliu Why is GPTSimpleVectorIndex better for large datasets? I thought that was the use case of the tree structure.

My use case by the way is indexing a large number of books on a subject for QA purposes. Thanks a bunch for your work on this. You're a first mover on this and are saving me a ton of time (if it works :)
