### ISSUE TITLE
add logging support

### ISSUE THREAD

**Issue by mcminis1** [jerryjliu/gpt_index#390]
todo:
- [x] add [logger + logging](https://docs.python-guide.org/writing/logging/#logging-in-a-library)
- [x] replace print statement as info or debug (to be reviewed during MR for appropriateness)
- [x] insert debug level logging for queries to LLMs

**Comment by mcminis1** [comment]
I'm thinking, get rid of verbose and use debug instead. Seem reasonable?

```python
        verbose = delete_kwargs.pop("verbose", False)
        full_delete = delete_kwargs.pop("full_delete", True)
        if verbose:
            print(f"> Deleting document: {doc_id}")
```
becomes
```python
logging.debug(f"> Deleting document: {doc_id}")
```


Perhaps use the verbose flag to log things like full text of things sent for embedding?

**Comment by jerryjliu** [comment]
thanks @mcminis1 for the help on this!
