### ISSUE TITLE
`pip install --upgrade gpt-index` producing different results when querying

### ISSUE THREAD

**Issue by silkspace** [jerryjliu/gpt_index#392]
Previous version (don't know which it was unfortunately) failed to import `from gpt_index.composability import ComposableGraph`

with error that composability did not exist. I upgrade and problem solved. 

When I reran my development jupyter notebook, summarization over the document store seems to summarize only a single document, rather than provide summaries over the corpus. 

Note: I am never using ComposableGraph -- this is at the level of GPTSimpleVectorIndex. Code worked well before upgrade.

**Comment by jerryjliu** [comment]
@silkspace could you share your code? i'm curious what parameters you're using

**Comment by silkspace** [comment]
The prototype:

Since encoding seems to have different effects, i split behavior here (for example, as dict, makes (batch, n_keys, embedding_dim) embedding vectors, versus if i concat, (batch, embedding_dim)) 

`def encode_record(row: pd.Series, cols, concat=True):
    if concat:
        res = ' '.join([str(row[col]) for col in cols])
    else:
        res = str({k:v for k,v in row.to_dict() if k in cols})
    return res`

helper to encode pandas df

`def process_directory(encode_df, concat=False):
    """Process a dataframe into a GPTSimpleVectorIndex"""
    from pathlib import Path
    with tempfile.TemporaryDirectory() as temp_dir:
        print(f'created temp directory: {temp_dir}')
        temp_dir = Path(temp_dir)

        cols = encode_df.columns
        for index, row in encode_df.iterrows():
            with open(temp_dir / (f"{index}.txt"), "w") as f:
                res = encode_record(row, cols, concat=concat)
                f.write(res[:MAX_CHUNK_SIZE])

        documents = SimpleDirectoryReader(temp_dir).load_data()
        index = GPTSimpleVectorIndex(documents)
    return index`

Factory method (to use GPTSimpleVector vs GPTList, but GPTList encoding is not queriable -- will file separately if this doesn't point out error). 

`def factory_index(df, cols, processor, loader, load, concat=False, pathfile=None):
    """Base function to create an index from a dataframe or load it from disk"""
    if df is None:
        load = True
        
    if not load:
        if cols:
            encode_df = df[cols]
        else:
            encode_df = df
        print(f'Processing dataframe of size {encode_df.shape}')
        #################################################
        index = processor(encode_df, concat=concat)
        #################################################
        print(f'Encoded dataframe as GPTListIndex')
        if pathfile:
            index.save_to_disk(pathfile)
            print(f'and saved it to {pathfile}')
    else:
        print(f'Opening {pathfile} - {loader}')
        index = loader.load_from_disk(pathfile)
    return index`

# the index
`def vector_df_index_processor(df: Optional[pd.DataFrame], pathfile: Optional[str], cols: Optional[List[str]] = None, concat: bool = False, load: bool = False):
    """Get a vector index from a dataframe or load from disk
    
    :param df (Optional): dataframe to encode, if None, then load from disk
    :param pathfile: path to save the index to, if None, then don't save
    :param cols: columns to encode, if None, then encode all columns
    :param load: whether to load the index from disk
    :param concat: whether to concatenate named columns into one string or make a string from a dictionary of dataframe's columns
    """
    index = factory_index(df, cols, process_directory, GPTSimpleVectorIndex, concat=concat, pathfile=pathfile, load=load)
    return index`
    
    
    
On a sample small reddit dataset, 

`index.query('summarize the corpus')` returns results from a single file, yet if I ask `index.query('what are main topics in machine learning subreddit')` it seems to come up with better responses. Previous responses (before upgrade) were good. 

Thanks.

**Comment by silkspace** [comment]
I understand more now. When I set `verbose=True, similarity_top_k=3` I see the interplay 

```
> Refine context: *some text*
> Refined response: ...etc

```
loop with top 3 vectors from the given query. Seems that in the code above it defaults to 1, hence the 'summary' was rather bland. That makes sense. 

The highest ranking first document, that produces the initial response, can heavily bias the direction of the summary, as it seems to append more context from further similarity documents to response, rather than do a full forward pass given the new context. 

Thanks, I think we can close this now.

**Comment by jerryjliu** [comment]
@silkspace for summaries (which i assume should go through the entire doc), you should use GPTListIndex with response_mode="tree_summarize", which will by default process every node

**Comment by jerryjliu** [comment]
I'm currently working on making it easier to do different types of queries!

**Comment by silkspace** [comment]
That @jerryjliu -- it's a great library and definitely the future!
