### ISSUE TITLE
How can I create an index with another embedding model?

### ISSUE THREAD

**Issue by batmanscode** [jerryjliu/gpt_index#399]
I went through the docs and tried the following:

```python
from gpt_index import SimpleDirectoryReader
from gpt_index import GPTSimpleVectorIndex
from langchain.embeddings.huggingface import HuggingFaceInstructEmbeddings
from gpt_index import LangchainEmbedding

embed_model = LangchainEmbedding(HuggingFaceInstructEmbeddings())

documents = SimpleDirectoryReader(input_files=['sample.txt']).load_data()

index = GPTSimpleVectorIndex(documents, embed_model=embed_model)
```

I get an error for not having an OpenAI key:
```
ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
```

I feel like there's something basic I'm doing wrong but I can't figure it out 🙁

**Comment by dtthanh1971** [comment]
import os
os.environ["OPENAI_API_KEY"] = 'YOUR_OPENAI_API_KEY'

**Comment by batmanscode** [comment]
> import os os.environ["OPENAI_API_KEY"] = 'YOUR_OPENAI_API_KEY'

I want to use another model, not OpenAI

**Comment by haowjy** [comment]
The llm_predictor is also specified when building the index, and the default is OpenAI. That is why you still need the API Key, I think.

**Comment by batmanscode** [comment]
> The llm_predictor is also specified when building the index, and the default is OpenAI. That is why you still need the API Key, I think.

I see, thanks!
