### ISSUE TITLE
gpt-index package doesn't work compiled with PyInstaller 

### ISSUE THREAD

**Issue by adamcohenhillel** [jerryjliu/gpt_index#403]
Need to add a VERSION file to the package so it will be picked correctly by pyinstaller

```
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gpt_index/__init__.py", line 4, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIAq2v8k/gpt_index/VERSION'
[1407] Failed to execute script 'main' due to unhandled exception!
```

**Comment by adamcohenhillel** [comment]
Might be due to older version. closing for now

**Comment by shirubei** [comment]
> Might be due to older version. closing for now

I ran into the same problem in windows 10 even with the newest V5.9 pyinstaller. Have you solved this problem ?

**Comment by shirubei** [comment]
After many times of tries, finally got a walk around.
Copy four folders(gpt_index, langchain, tiktoken_ext, tiktoken as listed below) from Lib\site-packages  under python installation folder.
The latter 2 are for "Unknown encoding gpt2". If this error didn't occur, then you can skip these two.
Add these line in the .spec file.

from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('gpt_index', include_py_files=True, includes=['**/*.*', '**/*'])
datas += collect_data_files('langchain', include_py_files=True, includes=['**/*.*', '**/*'])
datas += collect_data_files('tiktoken_ext', include_py_files=True, includes=['**/*.*', '**/*'])
datas += collect_data_files('tiktoken', include_py_files=True, includes=['**/*.*', '**/*'])

And compile with your spec file.
