### ISSUE TITLE
Setup chunk_size_limit

### ISSUE THREAD

**Issue by dtthanh1971** [jerryjliu/gpt_index#405]
How to setup a chunk_size_limit when I devided text in chunks to embed in Vector Database

# max LLM token input size
max_input_size = 500
# set number of output tokens
num_output = 48
# set maximum chunk overlap
max_chunk_overlap = 20

prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

index = GPTSimpleVectorIndex(documents, embed_model=embedding_llm, llm_predictor=llm_predictor, prompt_helper=prompt_helper)

**Comment by jerryjliu** [comment]
if the goal is just to set chunk_size_limit, all you have to do is set it when initializing the index class

`index = GPTSimpleVectorIndex(documents, chunk_size_limit=500)`
