### ISSUE TITLE
Google Scholar/ArXiv connectors

### ISSUE THREAD

**Issue by taesiri** [jerryjliu/gpt_index#411]
Hello and thanks for this amazing project.

I was wondering about the possibility of adding support for building an index out of Google Scholar and/or ArXiv search results. All the individual parts seem easy, but we don't have an easy way for that (obtaining the papers from the results => extracting the text from a PDF => creating the index). I am not sure about the general interest, but this can be very useful when searching for papers or doing a literature review.

Thanks

**Comment by ifrit98** [comment]
There exits an ArXiv API example here:

https://github.com/emptycrown/llama-hub/tree/main/loader_hub/papers/arxiv

**Comment by taesiri** [comment]
@ifrit98 Awesome! Thanks for the link.

**Comment by jerryjliu** [comment]
yep hope that works @taesiri!  - will close this issue unless there's anything else
