### ISSUE TITLE
Remove links to shorturl.at

### ISSUE THREAD

**Issue by mcminis1** [jerryjliu/gpt_index#417]
these links have been changed and no longer point to documentation.

- [ ] [langchain sql wrapper](https://github.com/jerryjliu/gpt_index/blob/3cf19e1e69c49b1aca243c01a515c410927709b5/gpt_index/langchain_helpers/sql_wrapper.py#L14)
- [ ] [Utility class for setting a temporary value for an attribute on a class](https://github.com/jerryjliu/gpt_index/blob/f17c8fe81a8e17a21629ce91a5682aee886a62ec/gpt_index/utils.py#L94)
- [ ] [adapted prompt from langchain](https://github.com/jerryjliu/gpt_index/blob/0fa608fe7dc2b8154e2cfe7ef8e7417565d4e8e6/gpt_index/prompts/default_prompts.py#L169)

**Comment by jerryjliu** [comment]
thanks for flagging this, i'll have a fix soon
