### ISSUE TITLE
Can you explain how to implement GPT_index for GPT-2 or GPT-j?

### ISSUE THREAD

**Issue by DanielShemesh** [jerryjliu/gpt_index#423]
I want to do this with an open-source model

**Comment by logan-markewich** [comment]
+1 ! Being able to use an open source model would be highly valuable

**Comment by jerryjliu** [comment]
we use langchain for the underlying LLM class so you could take a look at the docs to see if the LLM class supports open-source models: https://langchain.readthedocs.io/en/latest/reference/modules/llms.html

**Comment by logan-markewich** [comment]
LangChain easily supports custom LLMs. 

I think it would be useful at some point to include better code support for custom models (for both the LLM and embeddings).

```
import torch
from langchain.llms.base import LLM
from transformers import pipeline

class FlanLLM(LLM):
    model_name = "google/flan-t5-xl"
    pipeline = pipeline("text2text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})

    def _call(self, prompt, stop=None):
        return self.pipeline(prompt, max_length=9999)[0]["generated_text"]

    def _identifying_params(self):
        return {"name_of_model": self.model_name}

    def _llm_type(self):
        return "custom"
```

**Comment by Keith-Hon** [comment]
> LangChain easily supports custom LLMs (although custom models don't always follow the prompt instructions as well as OpenAI models)
> 
> I think it would be useful at some point to include better code support for custom models (for both the LLM and embeddings).
> 
> ```
> import torch
> from langchain.llms.base import LLM
> from transformers import pipeline
> 
> class FlanLLM(LLM):
>     model_name = "google/flan-t5-xl"
>     pipeline = pipeline("text2text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})
> 
>     def _call(self, prompt, stop=None):
>         return self.pipeline(prompt, max_length=9999)[0]["generated_text"]
> 
>     def _identifying_params(self):
>         return {"name_of_model": self.model_name}
> 
>     def _llm_type(self):
>         return "custom"
> ```

Thanks for the input. I have tried your codes but with SimpleVectorIndex and SimpleListIndex, it only works with SimpleListIndex tho.

**Comment by jerryjliu** [comment]
> Thanks for the input. I have tried your codes but with SimpleVectorIndex and SimpleListIndex, it only works with SimpleListIndex tho. Do you know how to provide embedding with huggingface's models?

you can also customize embeddings (including with langchain) here: https://gpt-index.readthedocs.io/en/latest/how_to/embeddings.html#custom-embeddings

**Comment by logan-markewich** [comment]
Thanks for the link @jerryjliu!

I should have spent more time looking at the docs. In addition to the embeddings, I see we can customize the LLM here: https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html

**Comment by jerryjliu** [comment]
np! going to close this issue for now unless you have other questions
