### ISSUE TITLE
Is there a way to provide OpenAI api_key at query / index time as a parameter?

### ISSUE THREAD

**Issue by neerajshah** [jerryjliu/gpt_index#425]
I would like to use different keys for different types of projects.

**Comment by emptycrown** [comment]
GPT Index uses the `LLM` class from LangChain so you can technically pass in a key if you want to. You can also just programmatically set the environment variable:
```python
os.environ["OPENAI_API_KEY"] = "xxxxxxx"
```

**Comment by hbchen121** [comment]
`GPT Index uses the LLM class from LangChain so you can technically pass in a key if you want to.`
Can you share the specific implementation of the bypass？
