### ISSUE TITLE
Return nodes/documents associated with a response.

### ISSUE THREAD

**Issue by ccfarah** [jerryjliu/gpt_index#430]
When returning a response, based on an index and query, e.g. response = index.query(query, response_mode="default"), it would be nice to have some traceback to the nodes and/or documents that contributed to the response (but not all nodes and documents that created the index). I can't really see a way to do this. Any thoughts would be appreciated.

**Comment by emptycrown** [comment]
If you look in the response, there should already be a `source_nodes` field that encapsulates this!

**Comment by ccfarah** [comment]
Thanks @emptycrown. I have used source_nodes, which appears to return all source nodes associated with the index, not just the nodes that generated the response. Ideally, I'd like the latter. For example, if a corpus is generated from books on Birds, Fish, and Mammals, and the query was, "How fast is an eagle", I'd like to return the formulated response, along with the Birds source.  How that makes sense.

**Comment by jerryjliu** [comment]
source_nodes should be just the nodes that generated the response. by default the chunk sizes are quite big, so source_nodes may contain all the text in the document.

try setting chunk_size_limit=512 (or some other low number) and looking at the index.query source_nodes results

**Comment by ccfarah** [comment]
Ah, that makes sense. My oversight. Thanks @jerryjliu for this awesome repo!
