### ISSUE TITLE
Chunk size can be negative

### ISSUE THREAD

**Issue by logan-markewich** [jerryjliu/gpt_index#447]
I'm using a custom prompt_helper, as follows:

```
# define prompt helper
# set number of output tokens
num_output = 512
# set maximum input size
max_input_size = 2048
# set maximum chunk overlap
max_chunk_overlap = 20

chunk_size_limit = max_input_size - num_output

prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
```

When running on the `paul_graham_essay` example, I get errors like this:

`ValueError: Got a larger chunk overlap (20) than chunk size (-77), should be smaller.`

The code should probably be preventing this from happening 🤔 I think it's because the prompt size is getting bigger than max_input_size

**Comment by jerryjliu** [comment]
Hey @logan-markewich, interesting, this actually shouldn't happen. How are you passing the prompt_helper into the index? Also could you try not setting the chunk_size_limit? We'll compute a default chunk size if you specify max_input_size and num_output

**Comment by logan-markewich** [comment]
@jerryjliu thanks for the suggestion! Unfortunately, it still happens when not setting `chunk_size_limit`

I am passing the prompt_helper as follows:
`index = GPTSimpleVectorIndex(documents, embed_model=embed_model, llm_predictor=custom_llm, prompt_helper=prompt_helper)`

Although admittedly, I am using `facebook/OPT-2.7B`, which seems to be terrible at following instructions and just rambles on. I think the model rambles so much that the context during the query becomes too large? Not 100% sure though for now. (Would not recommend this model for gpt_index though lol)
