### ISSUE TITLE
Is inserting documents to an index one by one slower than inserting the documents when setting up the index?

### ISSUE THREAD

**Issue by AdirthaBorgohain** [jerryjliu/gpt_index#450]
I am using GPTFaissIndex as my index and am trying to insert about 6 million texts into it. I am initializing an empty GPTFaissIndex index first. 

The texts are first fetched from a SQL database and I am iterating over the fetched data one by one. In each iteration, I am splitting the text using text_splitter.split_text() before inserting the generated documents into the index by using index.insert() method. This works well, but the speed of insertion is very slow. Is there any way to speed this up? Will inserting all the documents at the same time during the initialization of the index improve the speed?

Relevant code snippet is added below for reference:
```
faiss_index = faiss.IndexFlatL2(768)
index = GPTFaissIndex([], faiss_index=faiss_index, embed_model=embed_model)

for d in sql_data_generator():    # This function yields row by row from the SQL database. Each row consists of id, title, description, url and publication_date
    try:
        text_chunks = text_splitter.split_text(d['description'])  
    except ValueError:
        continue
    for text in text_chunks:
        embedding = embed_model.get_text_embedding(text)   
        document = Document(text, embedding=embedding, 
                                  extra_info={
                                      "id": d['id'],
                                      "title": d['title'],
                                      "url": d['url'],
                                      "publication_date": str(d['publication_date'])}
                                 )
        index.insert(document)
```

**Comment by jerryjliu** [comment]
@AdirthaBorgohain out of curiosity, is there a reason you want to split the text up yourself? if you just wrapped a Document around the fetched data, we would split the text up under the hood for you.

```
for d in sql_data_generator():
   doc = Document(d["description"])
   index.insert(document)
```

this wouldn't speed up runtime but makes the code a bit simpler.

regarding splitting up runtime, it might be because we need to call the openai embedding api for each text chunk. If you pre-compute embeddings for each document, you can specify that in the Document itself e.g. `Document(d["description"], embedding=embedding)`

**Comment by AdirthaBorgohain** [comment]
Hey thanks for replying. I used split up the text myself as I was following your `InsertDemo.ipynb` notebook for inserting documents into indexes. Also, it's probably my fault but I couldn't find it documented anywhere that wrapping the text in a document object would split it up. 
If say, d["description"] is a long text and I want to split it up into chunks of 512 length max, how do I do it  without using text_splitter?

Also, if I want to pre compute the embeddings through a different huggingface based model, say. Would I not need to split the long text beforehand so that I can generate the embedding of the split text rather than the whole complete long text before putting it into a document object?

**Comment by AdirthaBorgohain** [comment]
@jerryjliu Thanks for the reply. I was following the [InsertDemo.ipynb](https://github.com/jerryjliu/gpt_index/blob/main/examples/paul_graham_essay/InsertDemo.ipynb) notebook which used the text_splitter before creating Document objects from the generated chunks. If wrapping the Document around the fetched data internally splits up the data into chunks, is there a way we can pass the `chunk_size` and `chunk_overlap` parameters?

Also, as a method for computing embeddings for the documents, I am using a sentence-transformers model. If say the sentence-transformers model has a max_seq_len of 512, should I also put the chunk_size in the text_splitter to 512 then? Else, won't I lose information from the text if the text length is bigger than 512?

**Comment by jerryjliu** [comment]
> @jerryjliu Thanks for the reply. I was following the [InsertDemo.ipynb](https://github.com/jerryjliu/gpt_index/blob/main/examples/paul_graham_essay/InsertDemo.ipynb) notebook which used the text_splitter before creating Document objects from the generated chunks. If wrapping the Document around the fetched data internally splits up the data into chunks, is there a way we can pass the `chunk_size` and `chunk_overlap` parameters?

Yeah just set `chunk_size_limit` when building the index. 
```
index = GPTSimpleVectorIndex(documents, ..., chunk_size_limit=512)
```

> 
> Also, as a method for computing embeddings for the documents, I am using a sentence-transformers model. If say the sentence-transformers model has a max_seq_len of 512, should I also put the chunk_size in the text_splitter to 512 then? Else, won't I lose information from the text if the text length is bigger than 512?

Yeah that makes sense to me, you'll want to set the chunk size <= the max # tokens your embedding model + LLM model can handle. 

Going to close this issue for now since this is more of a question: if you have more questions please join the discord! https://discord.gg/dGcwcsnxhU
