### ISSUE TITLE
QdrantIndex loses client in composability

### ISSUE THREAD

**Issue by Mikkolehtimaki** [jerryjliu/gpt_index#461]
When creating a ComposableGraph over a composite index of Qdrant indices, queries error in

    File ...gpt_index/gpt_index/indices/query/vector_store/qdrant.py:61, in GPTQdrantIndexQuery.__init__(self, index_struct, embed_model, similarity_top_k, client, *
    *kwargs)
         58     raise ValueError(import_err_msg)
         60 if client is None:
    ---> 61     raise ValueError("client cannot be None.")
         63 self._client = cast(qdrant_client.QdrantClient, client)
    
    ValueError: client cannot be None.

Seems that the Qdrant client is not carried over to the composed index or graph. Created the query like this:

    i1 = GPTQdrantIndex([d1], client=client, collection_name="i1")
    i2 = GPTQdrantIndex([d2], client=client, collection_name="i2")
    li = GPTListIndex([i1, i2])
    graph  = ComposableGraph.build_from_index(li)

**Comment by Rohitjoshi9023** [comment]
Any update?

If anyone knows how we can use Vector Stores Indexes with ComposableGraph, please help
https://stackoverflow.com/questions/75549286/gpt-index-issue-using-composablegraph-with-vector-stores

**Comment by Mikkolehtimaki** [comment]
I dug in a bit, the clients (I assume this affects weaviate as well) are not part of index_struct that is copied over in composability, causing the error. If I read it right :) May be a bigger change needed to fix it.

**Comment by jerryjliu** [comment]
@Mikkolehtimaki let me know if this is still an issue! apologies for the delay, 0.4.15 should have fixed this https://discord.gg/dGcwcsnxhU
