### ISSUE TITLE
Get cosine score while querying index

### ISSUE THREAD

**Issue by abhishek22-ai** [jerryjliu/gpt_index#466]
Hi, Is there a way to overload or method available for index.query method to get the cosine score as well ?

**Comment by ymansurozer** [comment]
You can get the `source_nodes` from the response object and it will include the similarity score. Is this what you're looking for?

**Comment by jerryjliu** [comment]
yep! exactly what @ymansurozer mentioned.

**Comment by rhelsing** [comment]
@ymansurozer is it possible to query these source nodes without the call to the LLM? If I'm just using the response.source_nodes, I dont want the query function to waste time and resources.

**Comment by jerryjliu** [comment]
yeah just set `response_mode="no_text"` during the `index.query` call

**Comment by rhelsing** [comment]
@jerryjliu Thanks you!

**Comment by jerryjliu** [comment]
going to close this issue for now since seems resolved

**Comment by abhishek22-ai** [comment]
@ymansurozer  Thanks, I used the same method as you described but the source_nodes object has similarity=None ?

**Comment by ymansurozer** [comment]
@abhishek22-ai can you share your code?

**Comment by abhishek22-ai** [comment]
Is there a way to do similarity search without querying index ?
For eg: 
I have ListIndex with text and embeddings
I have query_str with its embeddings
Now, I just want to get the cosine score between query_str and ListIndex ?

**Comment by jerryjliu** [comment]
yes see above https://github.com/jerryjliu/gpt_index/issues/466#issuecomment-1436096393

**Comment by abhishek22-ai** [comment]
@jerryjliu  Hi, What might reason behind getting similarity=None in response object ? Thanks
