### ISSUE TITLE
Why do we send embedding requests to Open AI one by one (one for each chunk) instead of batching them in a few requests?

### ISSUE THREAD

**Issue by ymansurozer** [jerryjliu/gpt_index#470]
If I understand the codebase correctly, when I create an index, each chunk is sent as a single embedding request to Open AI, one after the other. However, we can batch them in an array and send the chunk array to Open AI in a single request, which is way faster. I tried, and creating a simple store index from a 100 pages document takes around a minute but with batching it takes 10 seconds. 

I know batching may cause issues for rate limits but we can create the chunks in a way to remain below 250k tokens per minute.

I really wonder the reason behind the current embedding strategy because I love the scability and scalability of GPT Index but it is slow even in small amounts of processing (even less than 50 pages).

**Comment by Smyja** [comment]
> If I understand the codebase correctly, when I create an index, each chunk is sent as a single embedding request to Open AI, one after the other. However, we can batch them in an array and send the chunk array to Open AI in a single request, which is way faster. I tried, and creating a simple store index from a 100 pages document takes around a minute but with batching it takes 10 seconds.
> 
> I know batching may cause issues for rate limits but we can create the chunks in a way to remain below 250k tokens per minute.
> 
> I really wonder the reason behind the current embedding strategy because I love the scability and scalability of GPT Index but it is slow even in small amounts of processing (even less than 50 pages).

I'd like to see your modifications.

**Comment by jerryjliu** [comment]
As a general note, we're working on reducing latency, and this could include request batching! Thanks for your patience @Smyja @ymansurozer
