### ISSUE TITLE
How can I pass custom prompt to ComposableGraph?

### ISSUE THREAD

**Issue by ashsha21** [jerryjliu/gpt_index#475]
Is there a way to pass a custom prompt to the composable graph. The query method take query config object but not able to figure out a way to pass in custom prompt ? 
The following statement failed.
res = indx.query(query_str,**text_qa_template= my_prompt**);

**Comment by jerryjliu** [comment]
yeah so in this seciton you see we can let the user specify query_configs, one for each index type: https://gpt-index.readthedocs.io/en/latest/how_to/composability.html#querying-the-top-level-index.

you'll want to specify something like 
```
{
...
"query_kwargs": {
  "text_qa_template": my_prompt,
}
...
}
```
in the query config corresponding to your index type

**Comment by jerryjliu** [comment]
going to close for now

**Comment by ashsha21** [comment]
it worked thanks.
