### ISSUE TITLE
How can I combine indexes or create a single index by using data with different data connectors?

### ISSUE THREAD

**Issue by eriktlu** [jerryjliu/gpt_index#480]
I want to pull data with different data connectors from multiple sources. Let's say I want data from my google docs, slack and a txt file. I understand how to do all of them one by one but what about if I want to create a single large index file that I can ask questions from?

What I tried was this kind of solution that I found from docs:

```
index1 = GPTSimpleVectorIndex(notion_docs)
index2 = GPTSimpleVectorIndex(slack_docs)

index1.set_text("summary1")
index2.set_text("summary2")

index3 = GPTListIndex([index1, index2])
```

But with this approach, the question/answer is not accurate anymore and does not find lots of things I am asking about that would work if I tried it on its own index only.

Another way that I tried that kind of worked was reading in all the documents and writing the content into a single file that I read in again later and index. But I would like to do it in a nicer way if possible.

Does anybody know how I can do this?

**Comment by jerryjliu** [comment]
> I want to pull data with different data connectors from multiple sources. Let's say I want data from my google docs, slack and a txt file. I understand how to do all of them one by one but what about if I want to create a single large index file that I can ask questions from?
> 
> What I tried was this kind of solution that I found from docs:
> 
> ```
> index1 = GPTSimpleVectorIndex(notion_docs)
> index2 = GPTSimpleVectorIndex(slack_docs)
> 
> index1.set_text("summary1")
> index2.set_text("summary2")
> 
> index3 = GPTListIndex([index1, index2])
> ```
> 
> But with this approach, the question/answer is not accurate anymore and does not find lots of things I am asking about that would work if I tried it on its own index only.
> 
> Another way that I tried that kind of worked was reading in all the documents and writing the content into a single file that I read in again later and index. But I would like to do it in a nicer way if possible.
> 
> Does anybody know how I can do this?

Hi @eriktlu to start with, you could try dumping all documents into a GPTSimpleVectorIndex e.g. with the quickstart tutorial: https://gpt-index.readthedocs.io/en/latest/

Re: composing a list index over simple vector indices, i just wanted to note that by doing this, you will query every SimpleVectorindex, and combine the responses. You may need to do a bit of prompt engineering to tell the LLM to "return 'unable to provide answer' if answer not found in the context" if you're going to try this approach.

**Comment by jerryjliu** [comment]
For more questions, please also consider joining the discord! https://discord.gg/dGcwcsnxhU

**Comment by jerryjliu** [comment]
going to close issue for now
