### ISSUE TITLE
Cannot find reference 'download_loader' in '__init__.py'

### ISSUE THREAD

**Issue by fredzannarbor** [jerryjliu/gpt_index#481]
```

from gpt_index import GPTListIndex, download_loader

PandasCSVReader = download_loader("PandasCSVReader")

```
`PyCharm Error:(5, 37) Cannot find reference 'download_loader' in '__init__.py'`

It does, however, run successfully.

**Comment by srinimanickam** [comment]
I tried this one too, but didn't work.
from gpt_index.readers.download import download_loader

**Comment by jerryjliu** [comment]
Hmm weird. I'm not sure, does this work without error in a normal python interpreter?

**Comment by emptycrown** [comment]
@srinimanickam @fredzannarbor Upgrading to latest version of gpt_index should fix the issue.

**Comment by mangate** [comment]
@emptycrown  I just used the latest version and getting the same error. Doesn't seem to work

**Comment by mangate** [comment]
ImportError                               Traceback (most recent call last)
Cell In [117], line 2
      1 import gpt_index
----> 2 from gpt_index import download_loader
      3 import os
      4 gpt_index.download_loader('NotionPageReader')

ImportError: cannot import name 'download_loader' from 'gpt_index' (c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\gpt_index\__init__.py)

**Comment by mangate** [comment]
Name: gpt-index
Version: 0.4.7

**Comment by jerryjliu** [comment]
@mangate does this work with a python interpreter?

**Comment by mangate** [comment]
Hi, this was solved, apparently installing gpt-index directly instead of llama-index solves this (I guess llama-index doesn't use the latest version of gpt-index)

**Comment by jerryjliu** [comment]
@mangate Ohhhh I see, you were using llama-index. 

Just a heads up, llamahub now uses llama_index imports by default. If you upgrade to the latest version (v0.4.8), please set `use_gpt_index_import=True` during the download_loader call. 

![download loader with apt index](https://user-images.githubusercontent.com/4858925/220289289-5c708d80-bbaa-44eb-84ef-9be9cf77cef5.jpeg)

will send out a broader announcement about this soon!
