### ISSUE TITLE
please fix mistake in custom_prompts.md

### ISSUE THREAD

**Issue by RaiAmanRai** [jerryjliu/gpt_index#483]
The example mentioned in the readme is a bit wrong and throws an error on running.
The same thing is mentioned on the documentation website.

```
SUMMARY_PROMPT_TMPL = (
    "Context information is below. \n"
    "---------------------\n"
    "{text}"
    "\n---------------------\n"
    "Given the context information and not prior knowledge, "
    f"answer the question: {query_str}\n"
)
```
On looking into the module, I found out the mistake.
The `{text}` shoud be replaced with `{context_str}`

**Comment by jerryjliu** [comment]
nice catch, will have a fix soon
