### ISSUE TITLE
how to pass keyword parameters along via index.query

### ISSUE THREAD

**Issue by fredzannarbor** [jerryjliu/gpt_index#498]
```
index = load_PandasCSV(args.input, args.output)
    if args.query and args.input:
        query_str = '''
[long custom prompt]
'''
        response = index.query(query_str)
```
Everything's working ok but the complex response is being cut off, presumably because the max tokens is too low, so I want to pass along a higher max_tokens value. How do I do that?  I tried query_config and query_kwarg but can't get the right formula.

**Comment by jerryjliu** [comment]
take a look here https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21
