### ISSUE TITLE
Question: Indexing an csv file

### ISSUE THREAD

**Issue by andyeung523** [jerryjliu/gpt_index#500]
Hi Jerry, really thanks for this amazing library. Recently I am trying to embedding a csv about different issues, it is containing ard 1200 row and 30 col, each row is a issue. 

I query with the index and found that the model answer wrongly, there are some answer with mismatch of different issue and not able to have a summarized view of the csv.

May I know the suggested embedding method in gpt_index for embedding such data structure ?

Here is my code: 

`
def construct_index(directory_path):
   
    print("start of the indexing")

    # set maximum input size
    max_input_size = 4096
    # set number of output tokens
    num_outputs = 256
    # set maximum chunk overlap
    max_chunk_overlap = 20
    # set chunk size limit
    chunk_size_limit = 600

    # define LLM
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003", max_tokens=num_outputs))
    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
 
    documents = SimpleDirectoryReader(directory_path).load_data()
    
    index = GPTSimpleVectorIndex(
        documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper
    )

    index.save_to_disk('index4.json')
    print("end of the indexing")

    return index
`

**Comment by jerryjliu** [comment]
hi @andyeung523, this is an interesting use case. tbh i'm not sure feeding the csv file into the SimpleDirectoryReader is the best way to solve this. what types of questions are you using? 

have you tried using the sql store instead? you can connect to a sql database with sqlalchemy https://github.com/jerryjliu/gpt_index/blob/main/examples/struct_indices/SQLIndexDemo.ipynb. You can connect it to an existing database, and set the input documents to a blank list. e.g. 
```
index = GPTSQLStructStoreIndex(
    wiki_docs, 
    sql_database=sql_database, 
    table_name="city_stats",
    llm_predictor=llm_predictor
)
```

**Comment by jerryjliu** [comment]
going to close this for now since now explicitly an issue - if you want to start a discussion thread please join the discord! https://discord.gg/dGcwcsnxhU
