### ISSUE TITLE
Is there a guidance on using  building a composite index vs updating the same index

### ISSUE THREAD

**Issue by ashsha21** [jerryjliu/gpt_index#503]
I am trying to figure out best way to create and then subsequently query where there are  updates to the knowledge base. There are two possible ways -
1) capture each update in seperate index and then create a wrapper composite index over them and then query comp index.
2) Keep updating the same index .

I tried both but interesting thing is I get difference answers to the query.

**Comment by jerryjliu** [comment]
yeah @ashsha21 different indices will induce different answers. Is there a specific issue you're facing? If it's a more general question about which indices to use, please check out the discord community! https://discord.gg/dGcwcsnxhU
