### ISSUE TITLE
Custom qa prompt is not working

### ISSUE THREAD

**Issue by abhishek22-ai** [jerryjliu/gpt_index#509]
Hi, I have been trying to run the below code with custom qa prompt template but it isn't working as expected
Below is the code:

`from gpt_index import Document
from gpt_index import GPTListIndex, LLMPredictor
from gpt_index.prompts.prompts import QuestionAnswerPrompt
from langchain import OpenAI

doc = Document("""
GPT Index (LlamaIndex) is a project consisting of a set of data structures designed to make it easier to use large external knowledge bases with LLMs.
NOTE: We are rebranding GPT Index as LlamaIndex! We will carry out this transition gradually.

2/19/2023: By default, our docs/notebooks/instructions now use the llama-index package. However the gpt-index package still exists as a duplicate!

2/16/2023: We have a duplicate llama-index pip package. Simply replace all imports of gpt_index with llama_index if you choose to pip install llama-index.

Github: https://github.com/jerryjliu/gpt_index

PyPi:
LlamaIndex: https://pypi.org/project/llama-index/.

GPT Index (duplicate): https://pypi.org/project/gpt-index/.

Twitter: https://twitter.com/gpt_index

Discord https://discord.gg/dGcwcsnxhU"""
)

        
llm_model = OpenAI(temperature=0, model_name="text-davinci-003")
llm_predictor = LLMPredictor(llm=llm_model)

dobby_prompt =  ("Context information is below. \n"
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "If unable to find answer from the context, say 'I dont know', else answer the question : {query_str}\n"
)

qa_prompt = QuestionAnswerPrompt(dobby_prompt)

index = GPTListIndex(doc, text_qa_template=qa_prompt, llm_predictor=llm_predictor)
index.query("Who is donald trump?")`

Thanks

**Comment by jerryjliu** [comment]
hi, what's the error that you're running into?

**Comment by abhishek22-ai** [comment]
According to template, I should get a response "I dont know" but the response is a brief summary about trump

**Comment by jerryjliu** [comment]
Oh I see. To be honest @abhishek22-ai this is more of a prompt engineering/davinci issue than a gpt index issue. You could try some prompt tuning to make the instructions more explicit (e.g. try "if the question is unrelated to the context..." etc.)

If you want to discuss further, ask in the discord! https://discord.gg/dGcwcsnxhU 

Going to close this GH issue since not explicitly gpt index related

**Comment by abhishek22-ai** [comment]
Okay thanks, I tried this with prompt engineering but didn't work out. Thank you for providing the discord link

**Comment by abhishek22-ai** [comment]
Hi @jerryjliu , As you suggested I tried doing prompt engineering and my final prompt is similar to prompt used in openai cookbook. 

"""Answer the question as truthfully as possible using the provided context, and if the answer is not contained within the text below, say "I don't know."\n\nContext:\n\n{context_str}\n\nQuestion:\n{query_str}\n\nAnswer:"""

I tested this prompt on openai playground, where the response is "I don't know"
But when the same prompt is used with gpt-index, i got a generative response

Is there a way in gpt-index to get the final prompt with complete context_str and query_str which is passed to llm, so that we can analyse?

**Comment by jerryjliu** [comment]
closing this issue for now. for more questions join the discord! https://discord.gg/dGcwcsnxhU

**Comment by abhishek22-ai** [comment]
@jerryjliu  Thanks for the help, It worked when i passed the text_qa_template in index.query
