### ISSUE TITLE
`query()` with streaming

### ISSUE THREAD

**Issue by TmLev** [jerryjliu/gpt_index#512]
Can `query()` stream the response? As in https://platform.openai.com/docs/api-reference/completions/create#completions/create-stream

If not, can it be achieved via a custom `QueryRunner`?

**Comment by jerryjliu** [comment]
ah we don't have streaming support yet, will keep you posted on when we do. there's been a few asks for this

**Comment by belyakov-am** [comment]
Also interested in this feature

**Comment by jerryjliu** [comment]
streaming now works! #603

**Comment by Jack-mi** [comment]
m
