### ISSUE TITLE
refactor _add_document_to_index in weaviate.py to use multithreaded batch import

### ISSUE THREAD

**Issue by hsm207** [jerryjliu/gpt_index#516]
The weaviate python client supports [multithreaded batch import](https://weaviate.io/developers/weaviate/client-libraries/python#new-multi-threading-batch-import-weaviate-client390) to import multiple documents in parallel.

We should refactor [_add_document_to_index](https://github.com/jerryjliu/gpt_index/blob/7125b16393728bc3da05c4d89d5977cc1ab4a59f/gpt_index/indices/vector_store/weaviate.py#L99-L113) to take advantage of this feature.

The current implementation creates [a batch size of 1](https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/readers/weaviate/data_structs.py#L227) and then [flushes it](https://github.com/jerryjliu/gpt_index/blob/7125b16393728bc3da05c4d89d5977cc1ab4a59f/gpt_index/readers/weaviate/data_structs.py#L143).

**Comment by jerryjliu** [comment]
Once https://github.com/jerryjliu/gpt_index/pull/514 lands hopefully should be solved!

**Comment by jerryjliu** [comment]
should be resolved in #557
