### ISSUE TITLE
[Breakage] extra_index in SimpleIndexDict returning None with newly serialized GPTSimpleVectorIndex

### ISSUE THREAD

**Issue by yunyu** [jerryjliu/gpt_index#519]
When upgrading from gpt-index==0.3.3 to llama-index==0.4.8, indexes saved with `GPTSimpleVectorIndex.save_to_disk` no longer persist `extra_info` correctly to documents.

Before: `extra_info` would be assigned correctly at the top level when `GPTSimpleVectorIndex.load_from_disk` is called

After: `extra_info` is not assigned to the SimpleIndexDict top level object, instead it needs to be accessed through `nodes_dict` which doesn't make sense, since each SimpleDictIndex in `GPTSimpleVectorIndex.docstore` should correspond to an individual document.

**Comment by jerryjliu** [comment]
Hi @yunyu how are you accessing the extra_info atm? Do you mean the extra_info in the Document itself? 

We no longer store the original Document in the docstore to save space in the index. The idea is that you could store the Document yourself if you wanted to.

let me know if that doesn't answer your question though

**Comment by yunyu** [comment]
I have a `GPTSimpleVectorIndex` loaded from disk:

```
source_doc = list(svi.docstore.docs.values())[0]
source_doc.extra_info
```

What's the current recommendation to store the document objects?

**Comment by jerryjliu** [comment]
Tbh there isn't a super sophisticated way since I figured the Document object was just an intermediate container in between your data source, and the index. The way you'd do it is just

```
doc_dict = document.to_dict()
json.dump(doc_dict, open('out.json', 'w'))
```

**Comment by yunyu** [comment]
Got it, wasn't aware of this design decision. Thanks for the clarification
