### ISSUE TITLE
How to use custom prompts and different default prompts?

### ISSUE THREAD

**Issue by eriktlu** [jerryjliu/gpt_index#522]
I can see only this example in the documentation: https://gpt-index.readthedocs.io/en/latest/how_to/custom_prompts.html

Does this mean it only works with GPTTreeIndex and not with GPTSimpleVectorIndex?

If I use it the same way on GPTSimpleVectorIndex I get an error:
`TypeError: BaseGPTIndex.__init__() got an unexpected keyword argument 'summary_template'`

My code:
```
query_str = user_text
prompt = (
"---------------------\n"
"{context_str}"
"\n---------------------\n"
"PROMPT TEXT"

f"Customer: {query_str}\n"
"AI:"
)

SUMMARY_PROMPT = SummaryPrompt(prompt)
index = GPTSimpleVectorIndex(documents, summary_template=SUMMARY_PROMPT)
```

And I can see there are lots of different default prompts found in [here](https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/prompts/default_prompts.py) but no example or explanation how to use them in the documentation.

I'd really like to use them just have no idea how.

**Comment by jerryjliu** [comment]
hi @eriktlu, thanks for the question. you can see the prompt "template" that each index uses during query time here (https://gpt-index.readthedocs.io/en/latest/reference/query.html - click into an index).

For example, here is the function signature for the list index query: https://gpt-index.readthedocs.io/en/latest/reference/indices/list_query.html#gpt_index.indices.query.list.GPTListIndexQuery. you can see that it takes in text_qa_template and refine_template

**Comment by jerryjliu** [comment]
for more questions join the discord! https://t.co/3ktq3zzYII

**Comment by jerryjliu** [comment]
going to close for now
