### ISSUE TITLE
Reduce package size with `options.extras_require` feature of setuptools

### ISSUE THREAD

**Issue by ajndkr** [jerryjliu/gpt_index#524]
At the moment, the package is quite heavy due to certain dependencies like `transformers`. This makes it difficult to deploy on serverless solutions like AWS Lambda.

Is it possible to create optional dependencies to make the package lightweight? https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

I have not dug too deep into the source code to understand if there are any optional dependencies but I think it would be quite beneficial from a DevOps perspective to tackle this problem.

**Comment by jerryjliu** [comment]
Yeah it's a good point, haven't had the chance through to comb for optional dependencies. If anyone does want to contribute in this direction let me know!

**Comment by ajndkr** [comment]
I can take a shot at this if you want. I would like to contribute.

**Comment by jerryjliu** [comment]
🙏

**Comment by ajndkr** [comment]
Can you please assign me to this issue then?

**Comment by ajndkr** [comment]
@jerryjliu I looked into the package and there are a lot of optional dependencies inside the `indices`, `readers` and `vector_stores` modules.

Right now, there's a try-catch block with an error message to install required dependencies. I think it's fine as-is. We just need to remove `transformers` from `install_requires` list as it is optional. 

Shall I open a PR for the same? If we want to add `extras_require`, we could create extras per module but then users will end up install a lot of redundant dependencies.

**Comment by jerryjliu** [comment]
Closed by #612

**Comment by chaoticgoodpanda** [comment]
<img width="1181" alt="Screenshot 2023-03-19 at 02 10 25" src="https://user-images.githubusercontent.com/13663360/226148390-fcdf31bb-d549-443a-8a9d-15731c4721b1.png">

Thanks so much for your ideas on this @ajndkr . If you can just get it down a *little* more it would make Vercel serverless deployment quick and easy. :) No worries if not possible!
