### ISSUE TITLE
How to retrieve documents within an index?

### ISSUE THREAD

**Issue by Kav-K** [jerryjliu/gpt_index#533]
Previously, before version 4.7, I was able to get individual documents from GPTSimpleVectorIndex like this:

```
[(_index.docstore.get_document(doc_id))
                    for doc_id in [docmeta for docmeta in _index.docstore.docs.keys()]]
```
Then, I was able to put this list into the constructor for `GPTTreeIndex` to make a new index using the contents of the GPTSimpleVectorIndex, now I can't do it anymore as it complains that the documents retrieved using this method are of type `IndexDict`. Is there a better way to do this now? How do I remake a GPTSimpleVector index (and the contents of multiple simple vector indexes) into a GPTTreeIndex?

**Comment by jerryjliu** [comment]
Hi @Kav-K, we recently (i think in 0.4.5) landed a refactor to the docstore to remove documents from being stored in the index, to reduce index storage size. this is because we wanted to limit the storage to just the index itself.

You can store the documents separately if you wish, and look them up through the retrieved doc_id of the source_node

**Comment by Kav-K** [comment]
Oh I see, thanks @jerryjliu. So, apart from storing the documents separately is there any other way you'd reccomend achieving this reformation of a simple index into a tree index? I want to give you some of my logic for why I wanna do this in the first place.

I have simple vector indexes and I want to turn them into tree indexes because tree indexes are more detailed and I can be more detailed with them by increasing the child depth factor as well. I can't use composable indexes because they only support composing from tree indexes, so I have been looking to put all the documents from the simple indexes into one tree index. Is there a less stupid way to do this?

**Comment by jerryjliu** [comment]
> Oh I see, thanks @jerryjliu. So, apart from storing the documents separately is there any other way you'd reccomend achieving this reformation of a simple index into a tree index? I want to give you some of my logic for why I wanna do this in the first place.
> 
> I have simple vector indexes and I want to turn them into tree indexes because tree indexes are more detailed and I can be more detailed with them by increasing the child depth factor as well. I can't use composable indexes because they only support composing from tree indexes, so I have been looking to put all the documents from the simple indexes into one tree index. Is there a less stupid way to do this?

hi @Kav-K , just to understand your use case a bit better, what do you mean by "I can't use composable indexes because they only support composing from tree indexes"? You can compose a tree index on top of simple vector indices.

How big is your document corpus? If it's very big then a raw tree index will be quite expensive. I'd recommend checking out whether you can do composability

**Comment by Kav-K** [comment]
@jerryjliu Oh, we can compose a tree index on top of GPTSimpleVectorIndex? How do I do that? I've been trying to figure it out but I haven't been able to. Would this mean that each simple vector index would consist a node of the tree, unlike if it were to be a raw tree index the document would be chunked up and the nodes would be the chunks?

**Comment by Kav-K** [comment]
I understand the way of doing it like this: https://github.com/jerryjliu/gpt_index/blob/main/examples/composable_indices/ComposableIndices.ipynb

But, for my size of data this is too broad of a composition, I'd rather have all the data be merged together and then put into a raw tree index, I understand the expense, it is more accurate though, right?

**Comment by jerryjliu** [comment]
> @jerryjliu Oh, we can compose a tree index on top of GPTSimpleVectorIndex? How do I do that? I've been trying to figure it out but I haven't been able to. Would this mean that each simple vector index would consist a node of the tree, unlike if it were to be a raw tree index the document would be chunked up and the nodes would be the chunks?

yes exactly! 

> I understand the way of doing it like this: https://github.com/jerryjliu/gpt_index/blob/main/examples/composable_indices/ComposableIndices.ipynb
> 
> But, for my size of data this is too broad of a composition, I'd rather have all the data be merged together and then put into a raw tree index, I understand the expense, it is more accurate though, right?

No actually I don't think that will be more accurate. generally speaking using one tree index is not scalable to larger corpuses of data. i'd always reocmmend starting out with one vector index, and then if you need more flexibility, try using composability

**Comment by jerryjliu** [comment]
Going to close this issue for now since seems unrelated to original question. For other questions please join the discord! https://discord.gg/xc2PG57U

**Comment by Kav-K** [comment]
Sounds good thank you!
