### ISSUE TITLE
Notion Loader for Database is only loading the first 100 page_ids

### ISSUE THREAD

**Issue by MarkusOdenthal** [jerryjliu/gpt_index#541]
Today during Testing of the Notion Loader I notices when I what load all pages from a Database that I get only the first 100 pages. The Notion API is return the attribute has_more and if this is true the are more pages we have to request.

I will work on a fix :)

**Comment by jerryjliu** [comment]
@MarkusOdenthal sounds good! if you can would love your submission on llamahub as we're deprecating the notion reader here (if not no worries, feel free to submit PR here and i can migrate) https://github.com/emptycrown/llama-hub

**Comment by MarkusOdenthal** [comment]
@jerryjliu, thanks for your fast response. I implemented a fix and made a submission on llamahub. So I will close this issue here.
