### ISSUE TITLE
Specify number of sources to return as part of response

### ISSUE THREAD

**Issue by ethankoch4** [jerryjliu/gpt_index#556]
How can I receive a response with text back from querying an Index while also specifying the number of source_nodes I want it to generate?

**Comment by logan-markewich** [comment]
If you are using a vector index, you can set the `similarity_top_k` option to the number you want (default is one)

**Comment by jerryjliu** [comment]
Yeah @ethankoch4 did you have something else in mind re: specifying number of source nodes? I'm trying to undersatnd the use case

**Comment by ethankoch4** [comment]
When I pass `similarity_top_k` into `GPTFaissIndex` I get an error - but I'd like to be able to either set it at instantiation time or when `.query` is called on the index

**Comment by jerryjliu** [comment]
> When I pass `similarity_top_k` into `GPTFaissIndex` I get an error - but I'd like to be able to either set it at instantiation time or when `.query` is called on the index

@ethankoch4 what's the error you're getting?

**Comment by ethankoch4** [comment]
ah, okay this works!
```python

embed_model = LangchainEmbedding(
    HuggingFaceEmbeddings(model_name="sentence-transformers/multi-qa-mpnet-base-dot-v1")
)
index = GPTFaissIndex(faiss_index=faiss.IndexFlat(768), embed_model=embed_model, index_struct=IndexDict())
text = "Today is Monday, February 27, 2023. This is example document {i}."
for i in range(10):
    index.insert(
        Document(text.format(i=i), doc_id="0", embedding=embed_model.get_text_embedding(text.format(i=i)))
    )

result = index.query("What day is it today?", similarity_top_k=10)
```


Previously I think I passed in `top_k` as an argument to `.query`. And looking at the source code it wasn't obvious to me that `similarity_top_k` would be respected either. https://github.com/jerryjliu/gpt_index/blob/6a7a29fe3aeff1acd52b53aa0a967c22481f11ff/gpt_index/indices/base.py#L339
