### ISSUE TITLE
How to handle Chinese corpus?

### ISSUE THREAD

**Issue by zhuxianqing** [jerryjliu/gpt_index#558]
If Chinese corpus is used directly, the index result seems unsatisfactory

**Comment by jerryjliu** [comment]
Hi @zhuxianqing, i'm actually not super familiar with gpt-3 on chinese. Do you happen to know good chinese LLM's? Can try plugging those into gpt index

**Comment by zhuxianqing** [comment]
> Hi @zhuxianqing, i'm actually not super familiar with gpt-3 on chinese. Do you happen to know good chinese LLM's? Can try plugging those into gpt index

ok, thanks

**Comment by imClumsyPanda** [comment]
@jerryjliu ChatGLM-6B might be a good choice among Chinese LLMs.
