### ISSUE TITLE
Cost estimator

### ISSUE THREAD

**Issue by teoh** [jerryjliu/gpt_index#56]
More of a nice-to-have.

Since building the index involves calls to GPT-3, it might be nice to have a verbose output option that counts the number of tokens involved, which will help devs get a feel for the costs involved with using this package.

**Comment by jerryjliu** [comment]
great idea!

**Comment by teoh** [comment]
Brainstorming a few ideas here.

This includes building the index and executing the query.
* Estimate cost _before_ making the call to the LLM. 
* Compute the exact cost _after_ making the call to the LLM. (Pretty sure we'll have this info)

**Comment by jerryjliu** [comment]
@teoh sure! that makes sense to me
