### ISSUE TITLE
WikipediaReader may be broken

### ISSUE THREAD

**Issue by hsm207** [jerryjliu/gpt_index#581]
This code:

```
from gpt_index.readers import WikipediaReader
WikipediaReader().load_data(["cats"])
```
returns the following exception:

> ConnectionError: HTTPConnectionPool(host='en.wikipedia.org', port=80): Max retries exceeded with url: /w/api.php?list=search&srprop=&srlimit=1&limit=1&srsearch=cats&srinfo=suggestion&format=json&action=query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff471bf1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

This code also returns the same error:

```
import wikipedia
wikipedia.summary("Wikipedia")
```

**Comment by jerryjliu** [comment]
@hsm207 seems like a spurious + rate-limit issue. i tried your code and it's working for me
