### ISSUE TITLE
Pip install fails: ERROR: Could not build wheels for numcodecs

### ISSUE THREAD

**Issue by bofinbabu** [jerryjliu/gpt_index#583]
```
ERROR: Failed building wheel for numcodecs
Failed to build numcodecs
ERROR: Could not build wheels for numcodecs, which is required to install pyproject.toml-based projects
```
PIp install fails with this errors.

Python 3.10.4

**Comment by jerryjliu** [comment]
@bofinbabu which OS are you on + how are you pip installing llama-index?

**Comment by hushujie** [comment]
I had a similar problem on MAC OS(M1), and more error msg is like:
`distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1. `

I solved this by using "conda install numcodecs==0.11.0" instead of "pip install numcodecs==0.11.0"

FYI

**Comment by jerryjliu** [comment]
thanks @hushujie for the help! @bofinbabu let us know if that works for you.

**Comment by jerryjliu** [comment]
@bofinbabu bump on this - going to close issue for now
