### ISSUE TITLE
GPTTreeIndex composition using a ChatGPTLLMPredictor fails

### ISSUE THREAD

**Issue by Kav-K** [jerryjliu/gpt_index#587]
```
                partial(
                    GPTTreeIndex,
                    documents,
                    embed_model=embedding_model,
                    llm_predictor=llm_predictor_deep,
                    use_async=True,
                ),
                ```
if I try to run this, where llm_predictor_deep is defined as
```
llm_predictor_deep = ChatGPTLLMPredictor()
```
It drops the error:
```
Traceback (most recent call last):
  File "/home/gptbot/cogs/search_service_cog.py", line 127, in search_command
    response, refined_text = await self.model.search(
  File "/home/gptbot/models/search_model.py", line 385, in search
    index = await self.loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/tree/base.py", line 74, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 278, in build_index_from_documents
    return self._build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/tree/base.py", line 124, in _build_index_from_documents
    index_graph = index_builder.build_from_text(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/common/tree/base.py", line 83, in build_from_text
    root_nodes = self.build_index_from_nodes(all_nodes, all_nodes)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/common/tree/base.py", line 118, in build_index_from_nodes
    outputs: List[Tuple[str, str]] = run_async_tasks(tasks)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/async_utils.py", line 12, in run_async_tasks
    outputs: List[Any] = asyncio.run(_gather())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/async_utils.py", line 10, in _gather
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/langchain_helpers/chain_wrapper.py", line 182, in apredict
    llm_prediction = await self._apredict(prompt, **prompt_args)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/langchain_helpers/chain_wrapper.py", line 162, in _apredict
    llm_chain = LLMChain(prompt=prompt.get_langchain_prompt(), llm=self._llm)
AttributeError: 'ChatGPTLLMPredictor' object has no attribute '_llm'
```

**Comment by jerryjliu** [comment]
> ```
>                 partial(
>                     GPTTreeIndex,
>                     documents,
>                     embed_model=embedding_model,
>                     llm_predictor=llm_predictor_deep,
>                     use_async=True,
>                 ),
>                 ```
> if I try to run this, where llm_predictor_deep is defined as
> ```
> 
> llm_predictor_deep = ChatGPTLLMPredictor()
> 
> ```
> It drops the error:
> ```
> 
> Traceback (most recent call last): File "/home/gptbot/cogs/search_service_cog.py", line 127, in search_command response, refined_text = await self.model.search( File "/home/gptbot/models/search_model.py", line 385, in search index = await self.loop.run_in_executor( File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/tree/base.py", line 74, in **init** super().**init**( File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 109, in **init** self._index_struct = self.build_index_from_documents(documents) File "/usr/local/lib/python3.9/dist-packages/gpt_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict f_return_val = f(_self, *args, **kwargs) File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 278, in build_index_from_documents return self._build_index_from_documents(documents) File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/tree/base.py", line 124, in _build_index_from_documents index_graph = index_builder.build_from_text( File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/common/tree/base.py", line 83, in build_from_text root_nodes = self.build_index_from_nodes(all_nodes, all_nodes) File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/common/tree/base.py", line 118, in build_index_from_nodes outputs: List[Tuple[str, str]] = run_async_tasks(tasks) File "/usr/local/lib/python3.9/dist-packages/gpt_index/async_utils.py", line 12, in run_async_tasks outputs: List[Any] = asyncio.run(_gather()) File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/usr/local/lib/python3.9/dist-packages/gpt_index/async_utils.py", line 10, in _gather return await asyncio.gather(*tasks) File "/usr/local/lib/python3.9/dist-packages/gpt_index/langchain_helpers/chain_wrapper.py", line 182, in apredict llm_prediction = await self._apredict(prompt, **prompt_args) File "/usr/local/lib/python3.9/dist-packages/gpt_index/langchain_helpers/chain_wrapper.py", line 162, in _apredict llm_chain = LLMChain(prompt=prompt.get_langchain_prompt(), llm=self._llm) AttributeError: 'ChatGPTLLMPredictor' object has no attribute '_llm'

hey! this is because this wrapper doesn't support async, it was an initial really hacky PR :) 

Maybe try using langchain's ChatGPT LLM implementation instead? It should plug in already

**Comment by jerryjliu** [comment]
actually @Kav-K  this should be pretty quick to add, one sec

**Comment by Kav-K** [comment]
Thanks! Also, quick question, for making a knowledgebase from web content scraped from the internet, would it be better to use a raw tree index or a knowledgebase index, for accuracy? @jerryjliu

**Comment by Kav-K** [comment]
Any way for me to get these changes into a new version without you re-releasing? When do you plan on releasing 4.18?

**Comment by jerryjliu** [comment]
yeah you can just clone the repo itself and try `pip install -e .` from within the repo
