### ISSUE TITLE
can not use chatgpt llm

### ISSUE THREAD

**Issue by starboyate** [jerryjliu/gpt_index#592]
documents = [Document(prompt)]
    llm_predictor = ChatGPTLLMPredictor(llm=OpenAI(temperature=0.5, model_name="gpt-3.5-turbo", max_tokens=1300))
    index = GPTSimpleVectorIndex(
        documents, llm_predictor=llm_predictor
    )

    summary = index.query("帮我输出一份报告")

TypeError: Object of type OpenAI is not JSON serializable

**Comment by jerryjliu** [comment]
the ChatGPTLLMPredictor is its own beta class, doesn't take in llm as an input. If you want to use langchain's chatgpt api, just use the regular LLMPredictor class instead

**Comment by jerryjliu** [comment]
closing for now, for more questions join the discord! https://discord.gg/dGcwcsnxhU
