### ISSUE TITLE
Langchain agent with Chatgptllm predictor

### ISSUE THREAD

**Issue by Smyja** [jerryjliu/gpt_index#595]
how can i use langchain with the [chatgpt llm predictor](https://github.com/jerryjliu/gpt_index/blob/main/examples/vector_indices/SimpleIndexDemo-ChatGPT.ipynb)? what needs to be modified in this?https://github.com/jerryjliu/gpt_index/blob/main/examples/langchain_demo/LangchainDemo.ipynb

**Comment by jerryjliu** [comment]
tbh my recommendation, just the langchain chatgpt one: 

```
# # LLM Predictor (gpt-3.5-turbo)
llm_predictor = LLMPredictor(llm=OpenAIChat(temperature=0, model_name="gpt-3.5-turbo"))
```
and plug the llm_predictor into the index during construction or query time 


going to close this issue since less of an issue and more of a usage question
