### ISSUE TITLE
`download_loader` incorrect typehint

### ISSUE THREAD

**Issue by MatthewCochrane** [jerryjliu/gpt_index#610]
The `download_loader` function specifies it's return type as an instance of `BaseReader` although it actually returns a `BaseReader` class and not an instance of one.  This leads to errors like the following:
![image](https://user-images.githubusercontent.com/11641643/222895420-3897e43e-f420-497a-9558-93ac6596963a.png)

**Comment by MatthewCochrane** [comment]
I created a PR to update this.  If someone could review that'd be helpful :)

**Comment by jerryjliu** [comment]
thanks!

**Comment by MatthewCochrane** [comment]
No problem!
