### ISSUE TITLE
How to retrieve the mapping between doc_id and file name?

### ISSUE THREAD

**Issue by onesecurity** [jerryjliu/gpt_index#613]
```
documents = SimpleDirectoryReader('data').load_data()
for doc in documents:
    print(doc)
```

[Document(text='text-content', doc_id='233dfb85-6a12-46b5-9010-xxx', embedding=None, extra_info=None)

How can I find the mapping relationship between doc_id and file name or file path if they are missing in Document object?

**Comment by jerryjliu** [comment]
You can define a `file_metadata` argument when initializing SimpleDirectoryReader; a function that takes in a filename as string and returns a dictionary of metadata.

```e.g.
file_metadata = lambda x: {"filename": x}
reader = SimpleDirectoryReader(..., file_metadata=file_metadata)
```

**Comment by kenn** [comment]
> You can define a `file_metadata` argument when initializing SimpleDirectoryReader; a function that takes in a filename as string and returns a dictionary of metadata.
> 
> ```
> file_metadata = lambda x: {"filename": x}
> reader = SimpleDirectoryReader(..., file_metadata=file_metadata)
> ```

When I do this, the filename is also prepended to `source_node.source_text` — how can I not add it to `source_text`? I'd like to scrub the directory path and show the file name only using the `extra_info`.

**Comment by Krumil** [comment]
Hello! is still the case with llama_index 0.5.0? Because i'm getting
`BaseGPTIndex.__init__() got an unexpected keyword argument 'file_metadata'`
When using this
`index = GPTSimpleVectorIndex.from_documents(documents, file_metadata=file_metadata)`

**Comment by skyler1ackerman** [comment]
> You can define a `file_metadata` argument when initializing SimpleDirectoryReader; a function that takes in a filename as string and returns a dictionary of metadata.
> 
> ```
> file_metadata = lambda x: {"filename": x}
> reader = SimpleDirectoryReader(..., file_metadata=file_metadata)
> ```

I'm having an issue with this where if the file_metadata function is provided, then the index file is much smaller. I think it only grabs the first X chunks from each file.
