### ISSUE TITLE
This File is Dangerous Message

### ISSUE THREAD

**Issue by RamBalani** [jerryjliu/gpt_index#622]
After I download from Github -- I am getting a 'This file is dangerous' message.
Is anyone else getting this when downloading gpt_index-main zip file ?
Is this safe Unzip locally on my computer ? Is there somethinf else I  need to do before I can work with Llamaindex to preview?

**Comment by logan-markewich** [comment]
It should be safe! But usually, you should do "git clone" if you want to get the could. This only really needs to be done if you are modifying the source code.

Otherwise, `pip install llama_index` works just fine

**Comment by jerryjliu** [comment]
yep +1! going to close issue for now

**Comment by RamBalani** [comment]
Got it working pip install llama_index FYI - wanted to poke around under the hood since we are new to all this -thanks for  acknowledging.
We're testing how our SmartSearch+ can interact with GPT-3 then Llamaindex (Gptindex) came along so we're looking at what this can do.
