### ISSUE TITLE
Empty Response after `index.query`

### ISSUE THREAD

**Issue by achempak-polymer** [jerryjliu/gpt_index#624]
In my workflow, I'm generating an index, saving it to S3, loading it later, and then re-generating the index from the saved data. In other words
```
index = GPTSimpleVectorIndex(docs)
index_str = index.save_to_string()
upload_to_s3(index_str, "test.json") # uses boto3 put_object

index_from_s3_bytes = load_from_s3("test.json") # output is a bytes object, and converting it to a string doesn't change anything; uses boto3 get_object
index_from_s3 = GPTSimpleVectorIndex.load_from_string(index_from_s3_bytes)
```

When I try doing `index_from_s3.save_to_string()`, I notice that `embedding_dict` is completely empty, where it was populated before. Furthermore, if I try doing index.query("Anything here"), I get `Empty Response` as a result. Does anyone know the reason my response is empty? I've attached the saved index in S3 below.
[502_Dalai Lama Test 3 Index.zip](https://github.com/jerryjliu/gpt_index/files/10897066/502_Dalai.Lama.Test.3.Index.zip)

This is what's shown in the logs after I query the index
```
> [query] Total LLM token usage: 0 tokens
INFO:root:> [query] Total embedding token usage: 9 tokens
> [query] Total embedding token usage: 9 tokens
```

**Comment by jerryjliu** [comment]
Hi @achempak-polymer, thanks for flagging. Taking a look soon!

**Comment by jerryjliu** [comment]
Hi @achempak-polymer, i just checked your json and embedding_dict is populated? Also i tested in a notebook with your json and it seems to work
<img width="1150" alt="Screen Shot 2023-03-06 at 11 36 39 AM" src="https://user-images.githubusercontent.com/4858925/223212827-8d0371ce-80e2-45ef-9578-b5978a161b9e.png">

**Comment by ankitb82** [comment]
Btw, I had a similar issue when I upgraded versions last week. Regenerating the index with the latest version solved it for me.

**Comment by jerryjliu** [comment]
sweet! will close the issue

**Comment by cg4213** [comment]
I run into this in a bit different way, if I run query simply through a py script ,everything is fine. but if I call the py script by spawn in nodejs. llm token count is 0, with empty response. any idea why?
