### ISSUE TITLE
Does Save_to_disk work for GPTChromaIndex

### ISSUE THREAD

**Issue by paulsiu1887** [jerryjliu/gpt_index#626]
I followed the docuementation and generated an index using Chroma and save it to disk. The index does work, but the save to disk does not appear to work. Does save_to_disk work for GPTChromaIndex? Here's an example of the code, the index generated appears to be missing the embedding information:

import chromadb
import os
from langchain import OpenAI
from llama_index import LLMPredictor, GPTChromaIndex, SimpleDirectoryReader

def open_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as infile:
        return infile.read()
os.environ["OPENAI_API_KEY"] = open_file('openaiapikey.txt')

chroma_client = chromadb.Client()
chroma_collection = chroma_client.create_collection('documents')

documents = SimpleDirectoryReader('data').load_data()
llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-embedding-ada-002"))
index = GPTChromaIndex(documents, llm_predictor=llm_predictor, chroma_collection=chroma_collection)
index.save_to_disk('index.json')

**Comment by jerryjliu** [comment]
Hey @paulsiu1887, thanks for raising. for vector store indices, `save_to_disk` just saves very basic information about the index, like the doc_id and summary text. The bulk of the info is stored within the chroma collection itself. 

Going to close this issue for now; for questions about usage please join our discord! https://discord.gg/dGcwcsnxhU

**Comment by jerryjliu** [comment]
yep! exactly. great feel free to follow up with more questions on the discord @paulsiu1887, i'll close this issue for now
