### ISSUE TITLE
Bump tenacity dependency version

### ISSUE THREAD

**Issue by creatorrr** [jerryjliu/gpt_index#632]
Currently this project depends on `tenacity<8.2.0` but that is preventing a lot of libraries from getting installed that depend on newer versions of `tenacity`. @jerryjliu is there any specific reason for this constraint? If not, then can we bump it up to `^8.2.2` (or `>=8.2.0,<9.0.0`) please?

**Comment by jerryjliu** [comment]
sounds good, will relax constraint
