### ISSUE TITLE
Is there any way to combine vector search and tree search?

### ISSUE THREAD

**Issue by Itto1992** [jerryjliu/gpt_index#636]
Thank you for creating such a great repo!
I am trying to implement my chatbot using this library.

I want to combine vector search and tree structure.
In other words, I want to create tree indices for each document (such as pdf) and register the summaries created by the tree indices to vector store. During query time, first search on the vector store to screen candidates and second look close at each document to answer a query.
Is there any way to realize this?

Thank you in advance!

**Comment by jerryjliu** [comment]
yes! the composability framework is exactly for this use case. take a look here: https://gpt-index.readthedocs.io/en/latest/reference/composability.html

**Comment by Itto1992** [comment]
Thank you for your reply! I appreciate it.

If there is any sample code, could you tell me the link?
I found examples of combining vector_store with keyword table [here](https://github.com/jerryjliu/gpt_index/tree/main/examples/composable_indices), but could not find an example of combining tree_index with vector_store.

**Comment by jerryjliu** [comment]
Hi @Itto1992, you can do something similar to that! Just do something like this:
```
tree_index1 = GPTTreeIndex([document1])
tree_index2 = GPTTreeIndex([document2])

vector_index = GPTSimpleVectorIndex([tree_index1, tree_index2, ...])
```

**Comment by jerryjliu** [comment]
going to close for now, for more questions join the discord! https://discord.gg/dGcwcsnxhU

**Comment by Itto1992** [comment]
Thank you for your invitation!
I will join.
