### ISSUE TITLE
config openai domain

### ISSUE THREAD

**Issue by yirenkeji555** [jerryjliu/gpt_index#640]
Due to restrictions in China, I need to forward API requests through other domain names. Which file do I need to configure?
For example: www.openai.com --> www.example.com

**Comment by Disiok** [comment]
I believe there are two possibilities.

1) you can configure it via the openai python client, following https://github.com/openai/openai-python
```
import openai
openai.api_type = "azure"
openai.api_key = "..."
openai.api_base = "https://example-endpoint.openai.azure.com"
openai.api_version = "2022-12-01"
```

2) via environment variables (see `https://github.com/openai/openai-python/blob/main/openai/__init__.py` 
```
api_key = os.environ.get("OPENAI_API_KEY")
# Path of a file with an API key, whose contents can change. Supercedes
# `api_key` if set.  The main use case is volume-mounted Kubernetes secrets,
# which are updated automatically.
api_key_path: Optional[str] = os.environ.get("OPENAI_API_KEY_PATH")

organization = os.environ.get("OPENAI_ORGANIZATION")
api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")
api_type = os.environ.get("OPENAI_API_TYPE", "open_ai")
api_version = (
    "2022-12-01" if api_type in ("azure", "azure_ad", "azuread") else None
)
```

**Comment by chrischjh** [comment]
It works by setting env vars, but the env var has to be set before importing llama_index libs

**Comment by billzhuang** [comment]
`export OPENAI_API_BASE=https://proxydomamin/v1`

works for me.

**Comment by LDY911** [comment]
> I believe there are two possibilities.
> 
> 1. you can configure it via the openai python client, following https://github.com/openai/openai-python
> 
> ```
> import openai
> openai.api_type = "azure"
> openai.api_key = "..."
> openai.api_base = "https://example-endpoint.openai.azure.com"
> openai.api_version = "2022-12-01"
> ```
> 
> 2. via environment variables (see `https://github.com/openai/openai-python/blob/main/openai/__init__.py`
> 
> ```
> api_key = os.environ.get("OPENAI_API_KEY")
> # Path of a file with an API key, whose contents can change. Supercedes
> # `api_key` if set.  The main use case is volume-mounted Kubernetes secrets,
> # which are updated automatically.
> api_key_path: Optional[str] = os.environ.get("OPENAI_API_KEY_PATH")
> 
> organization = os.environ.get("OPENAI_ORGANIZATION")
> api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")
> api_type = os.environ.get("OPENAI_API_TYPE", "open_ai")
> api_version = (
>     "2022-12-01" if api_type in ("azure", "azure_ad", "azuread") else None
> )
> ```
求问具体该如何修改呢

**Comment by mintisan** [comment]
just modify `openai.base` as below:

```
import openai

# proxies = {
#     'http': "http://127.0.0.1:7890",
#     'https': "http://127.0.0.1:7890"
# }
# openai.proxy = proxies
openai.log = "debug"

# Load your API key from an environment variable or secret management service
openai.api_key = os.getenv("OPENAI_API_KEY")

# openai.api_base = "https://oai.hconeai.com/v1"
openai.api_base = "https://openai.api2d.net/v1"

```

**Comment by ziXiong** [comment]
> just modify `openai.base` as below:
> 
> ```
> import openai
> 
> # proxies = {
> #     'http': "http://127.0.0.1:7890",
> #     'https': "http://127.0.0.1:7890"
> # }
> # openai.proxy = proxies
> openai.log = "debug"
> 
> # Load your API key from an environment variable or secret management service
> openai.api_key = os.getenv("OPENAI_API_KEY")
> 
> # openai.api_base = "https://oai.hconeai.com/v1"
> openai.api_base = "https://openai.api2d.net/v1"
> ```

seems like this works
