### ISSUE TITLE
Question about "SimpleDirectoryReader"

### ISSUE THREAD

**Issue by BrunoAPazetti** [jerryjliu/gpt_index#647]
Hi there!

In the documentatio (https://gpt-index.readthedocs.io/en/latest/how_to/data_connectors.html#data-connectors-llamahub) as stated that "SimpleDirectoryReader" can support parsing a wide range of file types: .pdf, .jpg, .png, .docx, **etc**.

What is in the "etc"? Do we have a complete list?

Tks!

**Comment by jerryjliu** [comment]
Take a look at the `DEFAULT_FILE_EXTRACTOR` variable here (you can also define your own!) https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/readers/file/base.py

**Comment by BrunoAPazetti** [comment]
Thank you!  I tried ".txt" as well, it looks like works fine. However, it is not listed in "DEFAULT_FILE_EXTRACTOR". Why does it works?

**Comment by jerryjliu** [comment]
> Thank you! I tried ".txt" as well, it looks like works fine. However, it is not listed in "DEFAULT_FILE_EXTRACTOR". Why does it works?

by default if not under file extractor we just load in the file contents as plain text

**Comment by BrunoAPazetti** [comment]
Thank you!!
