### ISSUE TITLE
ImportError: cannot import name 'Memory' from 'langchain.chains.base'

### ISSUE THREAD

**Issue by aldrinc** [jerryjliu/gpt_index#651]
Running the starter project on a a clean env but getting import errors.

Ran it on Apple MBP Pro M2 but recreated issue in Replit as well.

Sample repo:
https://replit.com/@AldrinClement/TestGPT

OPEN_API_KEY imported as secret in replit.

~/TestGPT$ python --version
Python 3.10.8

dep:
llama_index="^0.4.22"

Confirmed that I was using ver langchain-0.0.103.

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader
  File "/home/runner/TestGPT/venv/lib/python3.10/site-packages/llama_index/__init__.py", line 47, in <module>
    from llama_index.langchain_helpers.memory_wrapper import GPTIndexMemory
  File "/home/runner/TestGPT/venv/lib/python3.10/site-packages/llama_index/langchain_helpers/memory_wrapper.py", line 5, in <module>
    from langchain.chains.base import Memory
ImportError: cannot import name 'Memory' from 'langchain.chains.base' (/home/runner/TestGPT/venv/lib/python3.10/site-packages/langchain/chains/base.py)

**Comment by jerryjliu** [comment]
patching in a fix right now! fix is already merged in master

**Comment by jerryjliu** [comment]
llama-index==0.4.22.post1
