### ISSUE TITLE
Way to add information source for the responses?

### ISSUE THREAD

**Issue by GitHuberPilot** [jerryjliu/gpt_index#673]
Thanks for creating this amazing project. Generating knowledge and summary from the external data source has a great real-world application. I am wondering whether LlamaIndex can help provide the source for the summarized text if provided with indexed documents. Since LlamaIndex is partially powered by langchain which allows souring the answers (https://langchain.readthedocs.io/en/latest/modules/indexes/chain_examples/qa_with_sources.html), there should be a workaround this. But how? Thank you for your reply in advance!

**Comment by jerryjliu** [comment]
Hi, you can parse `response.source_nodes` after an `index.query(...)` call which should contain information about the source texts/documents. Is that what you're looking for?

**Comment by GitHuberPilot** [comment]
@jerryjliu This partially answered my question. Thank you!
