### ISSUE TITLE
chatml support

### ISSUE THREAD

**Issue by phiweger** [jerryjliu/gpt_index#674]
Is it possible to query an index with the (new) chatml syntax? like:

```
[
    {
        "role": "system", 
        "content" : "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\nKnowledge cutoff: 2021-09-01\nCurrent date: 2023-03-02"
    },
    {
        "role": "user", 
        "content" : "How are you?"
    },
    {
        "role": "assistant", 
        "content" : "I am doing well"
    },
    {
        "role": "user", 
        "content" : "What is the mission of the company OpenAI?"
    }
]
```

**Comment by jerryjliu** [comment]
If you use a chatgpt llm, then we'll use this message format! https://github.com/jerryjliu/gpt_index/blob/main/examples/vector_indices/SimpleIndexDemo-ChatGPT.ipynb

**Comment by logan-markewich** [comment]
@phiweger using the ChatGPTLLMPredictor class, the messages get built like that for you under the good 💪 so single string inputs are fine

**Comment by logan-markewich** [comment]
Technically, for list and vector indexes, the llm is not used during construction, so it's only needed at `query()` time @phiweger 

But, passing it to both won't hurt either
