### ISSUE TITLE
Question: GPT-neox

### ISSUE THREAD

**Issue by nawara72** [jerryjliu/gpt_index#677]
Hi 

Just wondering if you have any idea if i can use gpt-index with gpt-neox https://github.com/EleutherAI/gpt-neox?
It would save me a lot of time of learning and trying if you already have an answer.

Thanks again for all your help

**Comment by logan-markewich** [comment]
You can technically use any LLM you want! 

Here's a link where a model from huggingface is used: https://github.com/jerryjliu/gpt_index/issues/544

I'm not sure how well neox performs with this type of tool (I haven't tried it myself yet). You might have to look into defining your own custom prompts if the default tool isn't working well

**Comment by nawara72** [comment]
Thanks so much for your quick reply, I might give it a go 

And thanks for llamaindex, it is a great
