### ISSUE TITLE
SimpleDirectoryReader doesn't recursively load files under directories

### ISSUE THREAD

**Issue by Minweiwangaaaa** [jerryjliu/gpt_index#685]
SimpleDirectoryReader doesn't seem to recursively load files under directories. Can we add a -r parameter to recursively load all files under directories?

**Comment by jerryjliu** [comment]
try setting `recursive=True` when initializing SimpleDirectoryReader

**Comment by Minweiwangaaaa** [comment]
> try setting `recursive=True` when initializing SimpleDirectoryReader
~
