### ISSUE TITLE
prompt reached the max tokens

### ISSUE THREAD

**Issue by yongxin-ms** [jerryjliu/gpt_index#688]
I import 7 pdf files, total size is 173MB, when i query, sometimes there will be an error:

`
InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4106 tokens (3850 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
`

**Comment by Disiok** [comment]
This looks like a small bug in the way we estimate token usage. Should be fixed soon. 

In the meanwhile you can set `chunk_size_limit` to be a slightly smaller value (than 4097) when constructing the index to avoid this issue.

**Comment by fqx** [comment]
> This looks like a small bug in the way we estimate token usage. Should be fixed soon.
> 
> In the meanwhile you can set `chunk_size_limit` to be a slightly smaller value (than 4097) when constructing the index to avoid this issue.

This solution only works when similarity_top_k=1.
I have also tried reducing the max_input_size in PromptHelper, doesn't solve the problem.
Changing the LLM to GPT-3.5 could work.

I suspect openAI counts tokens differently, especially for CJK characters.
