### ISSUE TITLE
Is there an upper limit to the length of the "ask" method response string?

### ISSUE THREAD

**Issue by BrunoAPazetti** [jerryjliu/gpt_index#695]
When we create a Index using "GPTSimpleVectorIndex" the index becomes a class. So we can use the method "ask" of this class. Then we have a "response" as a result.

Is there an upper limit to the length of the ask method response string?

It seems to me that in some cases the response string is cut, when the sting response is big.

**Comment by logan-markewich** [comment]
@BrunoAPazetti the response string can be cut off, usually because the default max_tokens from a single OpenAI call is 256

See this page here for extending that: https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21

**Comment by Disiok** [comment]
@logan-markewich's answer is right on. Closing issue for now.

**Comment by BrunoAPazetti** [comment]
Thank you!

**Comment by jmcrook** [comment]
> @BrunoAPazetti the response string can be cut off, usually because the default max_tokens from a single OpenAI call is 256
> 
> See this page here for extending that: https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21

Seems like this link no longer works. Is there another resource that describes how to fix this issue?

**Comment by logan-markewich** [comment]
@jmcrook 

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21
