### ISSUE TITLE
(German) Language Option for Default Prompts

### ISSUE THREAD

**Issue by benheckmann** [jerryjliu/gpt_index#704]
Hi there! 

I am using LlamaIndex with german data and german prompts. As far as I can tell the default prompts are only in English and there is no option for setting the language. I suspect that a native language default prompt could avoid confusing the model and slightly improve performance. Has this been discussed/proposed before?

**Comment by Disiok** [comment]
Hey @benheckmann, yes the default prompts are only in English, but it's possible to set custom prompts (see https://gpt-index.readthedocs.io/en/latest/how_to/custom_prompts.html). 

We'd love to expand international language support in the future. If you are interested, we would encourage making a contribution via PR to benefit the community!

If you haven't, please join the discord community, you'd get quicker response and better support there! 

Closing this for now.
