### ISSUE TITLE
Document use of OpenAI API

### ISSUE THREAD

**Issue by jkitchin** [jerryjliu/gpt_index#76]
In trying to use this, you get an error if you haven't setup an OpenAI account with API key. That should probably be noted on the readme. I had to setup a paid account to use this. It would also be helpful to indicate what typical costs associated with this might be.

I did see there is some cost analysis in the index documenation (eg https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/indices/keyword_table/README.md#faqadditional).

**Comment by jerryjliu** [comment]
Good idea!

**Comment by jerryjliu** [comment]
linked in env setup: https://github.com/jerryjliu/gpt_index/issues/224
