### ISSUE TITLE
Going over the maximum context length when building an index

### ISSUE THREAD

**Issue by bockaerts** [jerryjliu/gpt_index#87]
Hey i'm getting an error when building an index because gpt_index is trying to go over the maximum context length.

`openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4169 tokens (3913 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.`

to reproduce:
```
from gpt_index import GPTTreeIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader('data').load_data()
index = GPTTreeIndex(documents)

# save to disk
index.save_to_disk('index.json')
```

on this data: https://github.com/awsdocs/amazon-quicksight-user-guide

**Comment by jerryjliu** [comment]
Oh! Weird, may be a flaw in the tokenizer / how I chunk up the data. I'll investigate

**Comment by jerryjliu** [comment]
By the way, @bockaerts, do you have the full stack trace? I think I have a hunch as to where it would be

**Comment by ArcadeCityMayor** [comment]
I encounter something similar. I'm trying to loop through a folder hierarchy and add each file to an index.

Warning at the top: `Token indices sequence length is longer than the specified maximum sequence length for this model (5446 > 1024). Running this sequence through the model will result in indexing errors`

Code:
```
index = GPTListIndex([])

def recursive_folder_search(folder):
    # get a list of all subdirectories in the given folder
    subdirectories = [f.path for f in os.scandir(folder) if f.is_dir()]

    # if there are no subdirectories, run the code
    if len(subdirectories) == 0:
        document = SimpleDirectoryReader(folder).load_data()[0]

        text_splitter = TokenTextSplitter(
            separator=" ", chunk_size=2048, chunk_overlap=20)
        text_chunks = text_splitter.split_text(document.text)
        doc_chunks = [Document(t) for t in text_chunks]

        # insert new document chunks
        for doc_chunk in doc_chunks:
            index.insert(doc_chunk)
    else:
        # if there are subdirectories, recursively call this function on each subdirectory
        for subdirectory in subdirectories:
            recursive_folder_search(subdirectory)


# call the function on the initial folder
recursive_folder_search('build')
```


Stack:

```
> Adding chunk: strict";
Object.defineProperty(exports, "__esMo...
Traceback (most recent call last):
  File "/Users/myuser/code/text2app/index.py", line 35, in <module>
    recursive_folder_search('build')
  File "/Users/myuser/code/text2app/index.py", line 31, in recursive_folder_search
    recursive_folder_search(subdirectory)
  File "/Users/myuser/code/text2app/index.py", line 31, in recursive_folder_search
    recursive_folder_search(subdirectory)
  File "/Users/myuser/code/text2app/index.py", line 31, in recursive_folder_search
    recursive_folder_search(subdirectory)
  [Previous line repeated 4 more times]
  File "/Users/myuser/code/text2app/index.py", line 18, in recursive_folder_search
    document = SimpleDirectoryReader(folder).load_data()[0]
  File "/Users/myuser/opt/miniconda3/lib/python3.9/site-packages/gpt_index/readers/file.py", line 33, in load_data
    data = f.read()
  File "/Users/myuser/opt/miniconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 41: invalid start byte
```

**Comment by jerryjliu** [comment]
@ArcadeCityMayor the latter issue should be fixed by this! https://github.com/jerryjliu/gpt_index/issues/88

**Comment by jerryjliu** [comment]
@ArcadeCityMayor re: the first issue, do you have a stack trace + is it erroring for you?

**Comment by ArcadeCityMayor** [comment]
> @ArcadeCityMayor re: the first issue, do you have a stack trace + is it erroring for you?

It doesn't error, just throws that as I guess a warning at the beginning of running the script. I'll try again shortly after trying the #88 fix and experimenting with my note above about using an incorrect separator.

![model](https://user-images.githubusercontent.com/14167547/206559839-29468044-be09-46ce-b6c7-86746c3e3183.png)

**Comment by ArcadeCityMayor** [comment]
Realized my directory traversal script included all my build files including node_modules. Once I copied over the specific folders I wanted into a new directory, the script ran fine.

I'm guessing in node_modules there were files that did not include the separator at all (like minified JS), and so the splitter was unable to reduce that to the desired chunk size.

Apologies if unrelated to OP. Thanks for your help!

**Comment by bockaerts** [comment]
Hey Jerry, sadly i didn't save the entire stack trace. I should've. I'd prefer not to rerun the indexing operation currently due to the cost (i'm working on trying to get my employer to pay for GPT but it might take me a while). I'll post again if this isn't solved by then.

**Comment by jerryjliu** [comment]
@bockaerts no worries! I'm working on some upgrades to how I parse tokens to deal with limitations as well, will keep you posted. 

In the meantime due to $$, i just wanted to point out that there are cheaper indices to try out, if you wanted to take a look. The following indices don't require GPT at all during building: 
- GPTListIndex
- GPTSimpleKeywordTableIndex - uses a regex keyword extractor
- GPTRAKEKeywordTableIndex - uses a RAKE keyword extractor

During query time, you also have a few different options to reduce GPT cost: 
- if using GPTListIndex, can do `index.query(..., keyword="<keyword>")` to filter out nodes that don't contain the keyword
- If using any GPTKeywordTableIndex subclass, you can do `index.query(..., mode="simple")` or `index.query(..., mode="rake")` to also use regex/RAKE keyword extractors on your query text.`
