### ISSUE TITLE
can't load data

### ISSUE THREAD

**Issue by ahmedriad1** [jerryjliu/gpt_index#92]
I have a txt file in `data/` and I'm trying to load it. However, it's failing:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/58295120/206767528-bf6d6ee3-0093-4b22-b062-8d7be628fa5b.png">

**Comment by jerryjliu** [comment]
hi @ahmedriad1, in #88 I added a PR to exclude dotfiles by default. Could you try upgrading to `pip install gpt-index==0.1.0`? (or pull the latest master)

Or you could just manually remove .ipynb_checkpoints

**Comment by ahmedriad1** [comment]
oh wait, the file was not showing when I ran `ls` but I tried deleting it anyways and it works now. Thanks @jerryjliu !

**Comment by jerryjliu** [comment]
Ok! closing this issue for now, let me know if anything else pops up
