### ISSUE TITLE
Use custom prompt

### ISSUE THREAD

**Issue by ahmedriad1** [jerryjliu/gpt_index#95]
I was wondering how can I use a custom prompt/template for the `index.query()` method.

**Comment by jerryjliu** [comment]
@ahmedriad1 good question! We're currently hard at work adding documentation, and a how-to for custom prompts is one of the main items.

In the meantime, I can help you directly. Which index are you using? I can send you a code snippet of the prompt templates, how to add it in as an argment.

**Comment by jerryjliu** [comment]
Should be resolved here: https://gpt-index.readthedocs.io/en/latest/how_to/custom_prompts.html
